### ISSUE TITLE
Consider using Ranger as the optimizer 

### ISSUE THREAD

**Issue by LifeIsStrange** [grammarly/gector#1]
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
It is a meta optimizer that achieve SOTA accuracy gains for free.
Ideally it should be combined with Mish activation function 

https://github.com/digantamisra98/Mish

**Comment by skurzhanskyi** [comment]
I guess that's a good idea to experiment with the latest optimizers and activation functions. Thanks for the proposal!
The main purpose of this repository is to provide an implementation of experiments conducted in the paper. These ideas go beyond the scope of our work.
But we will be glad if someone explores this opportunity and share results
