### ISSUE TITLE
custom dataset training

### ISSUE THREAD

**Issue by Ysmita** [grammarly/gector#10]
Hi,

If I wish to train the model on my dataset, How do I prepare the data? Kindly guide me in preparing the dataset

**Comment by skurzhanskyi** [comment]
Hi @Ysmita 
To train the model, you need to preprocess data to a particular format using `utils/preprocess_data.py`. It takes parallel files as input (`--source` and `--target` parameters).
If you're asking about tokenization, I guess it depends on the task. In our case, the data was already tokenized (https://www.cl.cam.ac.uk/research/nl/bea2019st/#instructions).

**Comment by Ysmita** [comment]
Hey..thanks for your reply. I actually wanted to know in what format the data in the source and target files are. Could you give me some ecamples?

**Comment by skurzhanskyi** [comment]
It's just a standard parallel files format, where each row in a source file corresponds to row in a target one.
For example, source file:
```I likes football .```
target file:
```I like football .```
For more real-life examples, please, check the link I sent before.
