### ISSUE TITLE
TypeError when training the model

### ISSUE THREAD

**Issue by tranthuykieu** [grammarly/gector#100]
I run the train.py file as follow to train the model:
python train.py --train_set /home/kieuttt/intern_m2/gector-models/gector/data-a1/train_syn_a1.txt \
		--dev_set /home/kieuttt/intern_m2/gector-models/gector/data-a1/dev_syn_a1.txt \
                --model_dir /home/kieuttt/intern_m2/gector-models/gector/data-a1

Then I got the problem like below. Anyone know how to fix it ??

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from allennlp.data.iterators import BucketIterator
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 7, in <module>
    from allennlp.common.checks import ConfigurationError
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/__init__.py", line 1, in <module>
    from allennlp.common.from_params import FromParams
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/from_params.py", line 48, in <module>
    from allennlp.common.params import Params
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/params.py", line 173, in <module>
    class Params(MutableMapping):
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/params.py", line 236, in Params
    def pop(self, key: str, default: Any = DEFAULT) -> Any:
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 67, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 93, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 114, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/signature.py", line 87, in ensure_signature_is_compatible
    super_sig, sub_sig, super_type_hints, sub_type_hints, is_static, method_name
  File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/signature.py", line 213, in ensure_all_positional_args_defined_in_sub
    f"`{method_name}: {sub_param.name} must be a supertype of `{super_param.annotation}` but is `{sub_param.annotation}`"
TypeError: `Params.pop: key must be a supertype of `<class 'inspect._empty'>` but is `<class 'str'>`

**Comment by MagdyLaban** [comment]
> I run the train.py file as follow to train the model:
> python train.py --train_set /home/kieuttt/intern_m2/gector-models/gector/data-a1/train_syn_a1.txt
> --dev_set /home/kieuttt/intern_m2/gector-models/gector/data-a1/dev_syn_a1.txt
> --model_dir /home/kieuttt/intern_m2/gector-models/gector/data-a1
> 
> Then I got the problem like below. Anyone know how to fix it ??
> 
> Traceback (most recent call last):
> File "train.py", line 6, in
> from allennlp.data.iterators import BucketIterator
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/**init**.py", line 1, in
> from allennlp.data.dataset_readers.dataset_reader import DatasetReader
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/dataset_readers/**init**.py", line 10, in
> from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 7, in
> from allennlp.common.checks import ConfigurationError
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/**init**.py", line 1, in
> from allennlp.common.from_params import FromParams
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/from_params.py", line 48, in
> from allennlp.common.params import Params
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/params.py", line 173, in
> class Params(MutableMapping):
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/allennlp/common/params.py", line 236, in Params
> def pop(self, key: str, default: Any = DEFAULT) -> Any:
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 67, in overrides
> return _overrides(method, check_signature, check_at_runtime)
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 93, in _overrides
> _validate_method(method, super_class, check_signature)
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/overrides.py", line 114, in _validate_method
> ensure_signature_is_compatible(super_method, method, is_static)
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/signature.py", line 87, in ensure_signature_is_compatible
> super_sig, sub_sig, super_type_hints, sub_type_hints, is_static, method_name
> File "/home/kieuttt/anaconda3/envs/test3.7/lib/python3.7/site-packages/overrides/signature.py", line 213, in ensure_all_positional_args_defined_in_sub
> f"`{method_name}: {sub_param.name} must be a supertype of `{super_param.annotation}`but is`{sub_param.annotation}`" TypeError: `Params.pop: key must be a supertype of `<class 'inspect._empty'>` but is `<class 'str'>`

I have the same problem here

**Comment by wshinigamic** [comment]
I have the same error as well, which seems to be a problem with `from allennlp.data.dataset_readers.dataset_reader import DatasetReader` in allennlp==0.8.4.

**Comment by HossamSmesm** [comment]
i have same error

**Comment by lakbhat** [comment]
The error is from [Overrides](https://pypi.org/project/overrides/) package. I think something is broken in the latest version. Try using an older version. 
`pip install overrides==4.1.2` fixed it for me.

**Comment by aneeshbhatb** [comment]
The error is from [Overrides](https://pypi.org/project/overrides/) package. I think something is broken in the latest version. Try using an older version. 
`pip install overrides==4.1.2` fixed it for me.

**Comment by tranthuykieu** [comment]
> The error is from [Overrides](https://pypi.org/project/overrides/) package. I think something is broken in the latest version. Try using an older version.
> `pip install overrides==4.1.2` fixed it for me.

Thanks @aneeshbhatb, it works for me, too.

**Comment by skurzhanskyi** [comment]
@aneeshbhatb, thanks so much for digging into the issue
You can create PR with the fix, we be happy to accept it :)

**Comment by mkorpela** [comment]
Please update to overrides 6.1.0 that solves this issue.
