### ISSUE TITLE
not working anything

### ISSUE THREAD

**Issue by mannan291** [grammarly/gector#102]
This model is not working for me. There is one error after the other. Libraries versions are not matching as well. 
I think old versions of libraries are the main reason for not working.
 It will be helpful if someone can guide me through.

**Comment by mannan291** [comment]
> This model is not working for me. There is one error after the other. Libraries versions are not matching as well. It will be helpful if someone can guide me through.

**Comment by skurzhanskyi** [comment]
Take a look at https://github.com/grammarly/gector/issues/100, there is fix https://github.com/grammarly/gector/pull/101

**Comment by skurzhanskyi** [comment]
`TypeError` should be fixed now
