### ISSUE TITLE
Why $KEEP exists one more time in labels? 

### ISSUE THREAD

**Issue by woong97** [grammarly/gector#103]
Thank you for publishing your brilliant repo. It's becoming too much of a study to me.

In processing_data.py,  convert_edits_into_labels function, I don't understand the result of this function.

$KEEP exists one more time in final labels. (line 230 in processing_data.py)

![image](https://user-images.githubusercontent.com/60849888/117873031-4f6b9f80-b2da-11eb-9a34-5755596ab302.png)

I think the correct labels in this case would be [['$KEEP'], ['$KEEP'], ['$DELETE'], ['$KEEP'], ['$KEEP'], ['$KEEP'], ['$KEEP'], ['$APPEND_When'], ['$KEEP'], ['$DELETE'], ['$KEEP']]. 
Am I wrong? Can you explain why $KEEP appears one more before "changed part"

Moreover, I don't know why "total_labels = len(source_tokens) + 1 "( line 251 in processing_data.py). Because of "+1" 
If source sentence equals target sentence, label is consisted of ['$KEEP'] and appear one more than length of source sentence.

**Comment by skurzhanskyi** [comment]
That's because we also have `$START` token. We just add it later
