### ISSUE TITLE
Are source correct txt file and target incorrect txt file in prerprocessing?

### ISSUE THREAD

**Issue by woong97** [grammarly/gector#104]
When I run "python utils/preprocess_data.py -s SOURCE -t TARGET -o OUTPUT_FILE", 

I think Source : correct txt file , Target: incorrect txt file. Is it right??

**Comment by skurzhanskyi** [comment]
It's vice versa: source - incorrect txt file (the one you want to feed to the model), target - correct txt file (the one you want to get as the model output).

**Comment by woong97** [comment]
Thank you for your comment!!
