### ISSUE TITLE
Start token is splited. Isn't it Bug?

### ISSUE THREAD

**Issue by woong97** [grammarly/gector#105]
In gector/wordpiece_indexer.py line 214 ~ 216,  "$START" token is splited into ['$', 'ST', 'ART'].
Thus bert input token always start with [1629, 4014, 11328, ~~~~] and bert-offsets is always [0, 3, ~~].

I think $START should be recognized to one token. Isn't it bug??
![image](https://user-images.githubusercontent.com/60849888/118144492-7c899080-b447-11eb-88ba-2336ab2922d0.png)

**Comment by skurzhanskyi** [comment]
Indeed, it's splited in the BERT model. That's why we have `special_tokens_fix` parameter. Still, it shouldn't significantly influence the quality
