### ISSUE TITLE
correct sentences of different lengths from wrong sentences

### ISSUE THREAD

**Issue by Lei-Xiangyu** [grammarly/gector#108]
Hello, I want to do incremental training on your model. I have a problem generating the dataset using utils/preprocess_data.py: Each corresponding sentence has to have the same length, but if we need the model to know how to split and merge, that means we need false sentences of different lengths from the correct ones, how do I do that?

**Comment by skurzhanskyi** [comment]
Did you find a solution? Or you still need help?
