### ISSUE TITLE
Splitting dataset into train/dev/test isn't much clear in README.

### ISSUE THREAD

**Issue by hojun0705** [grammarly/gector#110]
I have done python utils/preprocess_data.py -s incorrect.txt -t correct.txt -o output.txt.
Now I have the output.txt.
But from here your README jump to 

python train.py --train_set TRAIN_SET --dev_set DEV_SET  --model_dir MODEL_DIR

I wish to have more detailed guidance on the process. I only have output.txt file, not train, test, dev set at all. How should I make the split sets? and the model_dir seems to be a directory where I put a file downloaded from [link] you colored as blue? Please give me some clear guidance on it?

Thank you.

**Comment by skurzhanskyi** [comment]
Hi 
In our experiments, we had 98/2 train/dev random split.
You may use the same technique or the one which is better for your task.
 `--model_dir` is the path to the directory where all data (weights, vocabulary) will be saved
To start from pretrained model use `--pretrain` and `--pretrain_folder` parameters:
https://github.com/grammarly/gector/blob/master/train.py#L140-L141
