### ISSUE TITLE
out of memory（RAM）

### ISSUE THREAD

**Issue by pengyuan101** [grammarly/gector#113]
when i trained model of stage I，my program is always Killed 。at  the same times,the GPU memory is always in low occupancy
![图片](https://user-images.githubusercontent.com/51777276/124249100-1fac7b80-db56-11eb-8178-c656b80157f2.png)
Reading your code, I found that you didn't put the data on the GPU memory. Is there anything special about this?

**Comment by skurzhanskyi** [comment]
Hi @pengyuan101 
AllenNLP puts the data on the GPU memory. Not sure how we can fix this.

**Comment by skurzhanskyi** [comment]
You can also try increasing the number of `max_instances_in_memory`. It looks like the training dies at this point.
https://github.com/grammarly/gector/blob/master/train.py#L155

**Comment by Chunngai** [comment]
Hello. I met the same problem. Have you fixed it?
