### ISSUE TITLE
Gector on CPU

### ISSUE THREAD

**Issue by Bala534** [grammarly/gector#115]
How can we reduce the running time of Gector model on CPU. Is there any ways to do that??

In GPU it was taken approximately 5 minutes whereas in CPU it taken upto 4 hours and is still running, With an input of approximately 40000 sentences....

On GPU

![2021-07-13](https://user-images.githubusercontent.com/72618397/125416086-0a114102-b4c3-4fcb-aa13-12f3de20afd3.png)

On CPU

![2021-07-13 (1)](https://user-images.githubusercontent.com/72618397/125416163-9f43f4e1-5b87-47a3-ab8e-202c60294494.png)

Links to my colab files:

1.https://colab.research.google.com/drive/1enUND0msUNCYySRpyCujGwBVBl6g1xjB?usp=sharing
2.https://colab.research.google.com/drive/1UAbp-iGd8RGz5JlUEIhqy-nIwK2Ud1mV?usp=sharing

**Comment by skurzhanskyi** [comment]
Transformers run much faster on GPU, as expected. To speed up it on the CPU you can try [quantization](https://pytorch.org/docs/stable/quantization.html), but I would expect significant gain
