### ISSUE TITLE
last 4 layers of bert

### ISSUE THREAD

**Issue by ylinlinz** [grammarly/gector#116]
Hi, how can I use last 4 layers of bert in your code？ I guess there is a parameter named self._scalar_mix which can achieve it in 'bert_token_embedder.py', but I have no idea about how to value the _scalar_mix. Thank you.

**Comment by skurzhanskyi** [comment]
There's no specific parameter for that, but you can use `transformer` model [here](https://github.com/grammarly/gector/blob/master/gector/bert_token_embedder.py#L74) to tweak the code
