### ISSUE TITLE
something error for prediction 

### ISSUE THREAD

**Issue by zjjhit** [grammarly/gector#118]
Hi There,
Thanks for this great repository.
Now when I try to use xlnet_0_gector.th to predict text , I get this error:
![image](https://user-images.githubusercontent.com/12822308/126461076-d8d998d7-082c-4499-b550-59f248895dba.png)
i used the command 'python predict.py --model_path xlnetmodel/xlnet_0_gector.th --input_file test --output_file out --transformer_model xlnet --special_tokens_fix 0'
Can you please help me how to debug it?   Thanks a lot.

**Comment by skurzhanskyi** [comment]
You need to specify `--vocab_path` here.

**Comment by skurzhanskyi** [comment]
For the models we published, you can use `data/output_vocabulary/`
