### ISSUE TITLE
Fine-tuning pretrained models (BERT, ROBERTA, XLNET) on another dataset

### ISSUE THREAD

**Issue by EvgeniaYangulova** [grammarly/gector#119]
Hi!

I would like to fine-tune your pretrained models on the dataset I have (contains approximately 25000 sentences). The question is how exactly it has to be done, there were some related issues, however, they never mentioned pretrained models. Should the command look like this?
python train.py --train_set train_file.txt --dev_set test_file.txt \
                         --model_dir MODEL_DIR_TRAIN\
                         --tune_bert: 1\
                         --skip_correct: 1\ 
                         --skip_complex: 0\
                         --max_len: 50\
                         --min_len: 3\  
                         --batch_size: 64\  
                         --tag_strategy: keep_one\
                         --cold_steps_count: 0\  
                         --cold_lr: 1e-3\  
                         --lr: 1e-5\  
                        --predictor_dropout: 0.0\  
                        --lowercase_tokens: 0\
                        --pieces_per_token: 5\  
                        --vocab_path: data/output_vocabulary\ 
                        --label_smoothing: 0.0\
                        --patience: 0\
                        --transformer_model: bert\
                        --accumulation_size: 2\  
                        --updates_per_epoch: 0\ 
                        --tn_prob: 1\  
                        --tp_prob: 1\  
                        --pretrain: bert_0_gector.th
And since you have specified that it is possible to use multiple transformer models, can I fine-tune all three transformer models at once? If yes, what should I change in the command?

**Comment by skurzhanskyi** [comment]
Hi, sorry for the late reply.

According to [this line](https://github.com/grammarly/gector/blob/master/train.py#L141), you should provide just `bert_0_gector` as a `pretrain`, and the path to the directory as a `pretrain_folder`.

You cannot fine-tune all models at once with our code. But you may rewrite it for distributional parallel training.

**Comment by WANG-Yuchen-Alice** [comment]
Hi, I am trying to pretrain using `python train.py --train_set data/train.txt --dev_set data/dev.txt --model_dir model_1104 --tune_bert 1 --skip_correct 1 --skip_complex 0 --max_len 50 --batch_size 64 --tag_strategy keep_one --cold_steps_count 0 --cold_lr 1e-3 --lr 1e-5 --predictor_dropout 0.0 --lowercase_tokens 0 --pieces_per_token 5 --vocab_path data/output_vocabulary --label_smoothing 0.0 --patience 0 --transformer_model bert --accumulation_size 2 --updates_per_epoch 0 --tn_prob 1 --tp_prob 1 --pretrain bert_0_gectorv2 --pretrain_folder pre_trained_model
`
but got the following size-mismatch error. May I seek your help regarding this case?
<img width="960" alt="Screenshot 2021-11-04 at 10 52 35 AM" src="https://user-images.githubusercontent.com/45040630/140249974-cb3eb2dc-25cd-4177-815e-e65ab5820003.png">

Thank you and look forward to hearing from you :)

**Comment by tharshita** [comment]
Hi! I am trying to pretrain the roberta model using the following command:
`python train.py --train_set data/train.txt --dev_set data/dev.txt --model_dir model_1104 --tune_bert 1 --skip_correct 1 --skip_complex 0 --max_len 50 --batch_size 64 --tag_strategy keep_one --cold_steps_count 0 --cold_lr 1e-3 --lr 1e-5 --predictor_dropout 0.0 --lowercase_tokens 0 --pieces_per_token 5 --vocab_path data/output_vocabulary --label_smoothing 0.0 --patience 3 --transformer_model bert --accumulation_size 2 --updates_per_epoch 0 --tn_prob 1 --tp_prob 1 --pretrain roberta_1_gectorv2 --pretrain_folder pre_trained_model --special_tokens_fix 1`

but got the following size-mismatch error. May I seek your help regarding this case please?

![ss](https://user-images.githubusercontent.com/46225963/140253329-174624d9-bd9b-41f5-885c-422f23e73401.jpg)

Thank you for your help and look forward to hearing from you! :)

**Comment by skurzhanskyi** [comment]
@tharshita You also need to specify `--vocab_path` parameter.
