### ISSUE TITLE
role of tokenizer in the prediction stage

### ISSUE THREAD

**Issue by joy-ko** [grammarly/gector#12]
Hi, 

I am curious about the role of tokenizer.

as far as I know, 
the model only use labels as vocabulary set both in the training and prediction stage, .

Therefore, vocab file of each model is in fact not used here,
but the vocabulary extracted from the data is used. 

If my understanding is right, what is the role of tokenizer(especially in the prediction stage)?

**Comment by skurzhanskyi** [comment]
Hi @joy-ko 
We extracted vocabulary one time and then used it at all stages. Changing the vocabulary can make the model predict nonsense. 
Could you please specify your question about the tokenizer? Which particular tokenizer do you mean?

**Comment by joy-ko** [comment]
Thanks for the reply. 

I was trying to apply the code to other custom data. 
And then, I got confused how should I preprocess the data and how the vocab works.

For confirmation, 
the vocab file of each model (bert, roberta, xlnet) is in fact used during the tokenizing and embedding process. 
isn't it? 
(because the code load the tokenizer from the pretrained model as we can see in "wordpiece_indexer.py" [line 409-410])

![image](https://user-images.githubusercontent.com/59045380/86764054-bbf68c00-c082-11ea-9582-df16bbdecfdf.png)

**bert_tokenizer = AutoTokenizer.from_pretrained(pretrained_model, do_lower_case=do_lowercase, do_basic_tokenize=False)**

**Comment by skurzhanskyi** [comment]
Yes, you're right. We use [huggingface's transformers library](https://github.com/huggingface/transformers), where indeed Tokenizers use model-specific vocabularies under the hood.
All the [data](https://www.cl.cam.ac.uk/research/nl/bea2019st/#data) used for training was tokenised (preprocessed) using spaCy v1.9.0 and the `en_core_web_sm-1.2.0` model. So you may also want yo use it as preprocessing. At the same time, from my point of view, preprocessing here is not so critical, as model-specific tokenization happens after all.

**Comment by joy-ko** [comment]
I got it! Thank you
