### ISSUE TITLE
Training problems.

### ISSUE THREAD

**Issue by Zecheng-Tang** [grammarly/gector#121]
Hi, thanks for your great work. After I preprocessed the data and got the output file train.label and valid.label, I tried to use these two files to train a new BERT model. However, I find the program always stopped at this line `model = model.to(device)`. There is no  error report but the used memory in the GPU remains unchanged (a little bit increasing step by step but too slowly !!).  Finally, the model is loaded to the GPU, but during the training, I got the error report:
```
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)
```

I check for a long time but can't figure out waht's wrong with my scripts or training process . I put my scripts below.

Preprocess: 

```
python utils/preprocess_data.py -s train.src -t train.trg -o train.label
python utils/preprocess_data.py -s valid.src -t valid.trg -o valid.label
```

Train

```
python train.py --train_set ./train.label  --dev_set ./valid.label \
--model_dir ./  --transformer_model bert 
```

Hope for your suggestion, thank you.

**Comment by skurzhanskyi** [comment]
Looks like a repository-unrelated issue.
I would suggest following this [thread](https://discuss.pytorch.org/t/cublas-status-execution-failed-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/116740/16).

**Comment by alsabahi2030** [comment]
@skurzhanskyi any good news on this? Thank you.

**Comment by Zecheng-Tang** [comment]
> @skurzhanskyi any good news on this? Thank you.

Hi, did you face the samiliar problem like me ?
