### ISSUE TITLE
For Grammar Error Correction task, why F0.5 is consider for evaluation and not F1? (Giving twice weight to precision than recall)

### ISSUE THREAD

**Issue by chayan-dhaddha** [grammarly/gector#123]

**Comment by skurzhanskyi** [comment]
It's just a common consensus that precision is more important for this particular task. I believe some papers show that F0.5 correlates better with human judgment than F1.

**Comment by skurzhanskyi** [comment]
Take a look at this paper: https://aclanthology.org/D15-1052.pdf
