### ISSUE TITLE
Questions about parameters.

### ISSUE THREAD

**Issue by Chunngai** [grammarly/gector#128]
Hi. Thanks for your great work and for your kindly releasing the source code. But I have some questions.
i) What's the parameters used (common & specific)? In "training_parameters.md" you only mentioned params for XLNet and RoBERTA.
ii) I should set `special_tokens_fix` to 0 for the BERT model, right? You have not mentioned that in the "training_parameters.md" file (even for the XLNet model).

**Comment by skurzhanskyi** [comment]
Hi @Chunngai 
In `training_parameters.md` for each stage, we show parameters for BERT, and for RoBERTa and XLNet we show model-specific params. As `spetial_tokens_fix` was not mentioned in stage parameters for BERT, `spetial_tokens_fix` had a default value, which is 0.

**Comment by skurzhanskyi** [comment]
By the way, we have links for uploading trained models' weight in the https://github.com/grammarly/gector#pretrained-models section.

**Comment by Chunngai** [comment]
@skurzhanskyi 
So to train a BERT GEC model the params in each stage should be:
i) stage 1: 
    a) 20 epochs + 3 patience (as in "Number of epochs and early stopping" in "training_parameters.md")
    b) Params of "Same parameters for all stages" in "training_parameters.md"
    c) Params of "Stage1 parameters" in "training_parameters.md"
    d) `special_tokens_fix == 0`
ii) stage 2:
    a) 20 epochs + 3 patience
    b) Params of "Same parameters for all stages"
    c) Params of "Stage2 parameters"
    d) `special_tokens_fix == 0`
iii) stage 3:
    a) 20 epochs + 3 patience
    b) Params of "Same parameters for all stages"
    c) Params of "Stage3 parameters"
    d) special_tokens_fix == 0

For prediction the params in each stage should be:
    a) Params of "For prediction during stage1-3 we used" in "training_parameters.md"
    b) `special_tokens_fix == 0`
And "Same parameters for all stages" is NOT for prediction in each stage.

Is that right?

**Comment by skurzhanskyi** [comment]
We had fewer epochs for stage 2 and stage 3, similar to RoBERTa and XLNet.
You're right; we're missing some information for BERT.

**Comment by Chunngai** [comment]
@skurzhanskyi Ok thanks. 
So can I set `n_epoch == 20` in the 2nd and 3rd stage, as `patience == 3` may stop the training somewhere? Or could you provide epoch info for BERT?

**Comment by skurzhanskyi** [comment]
I think yes

**Comment by skurzhanskyi** [comment]
Best parameters for final predictions you can find at https://github.com/grammarly/gector#pretrained-models

**Comment by Chunngai** [comment]
Ok thanks. I'll try it.
