### ISSUE TITLE
min_len in training

### ISSUE THREAD

**Issue by Chunngai** [grammarly/gector#129]
It seems that `min_len` is not a param in "train.py". But "Same parameters for all stages" in "training_parameters.md" provides it (`--min_len: 3`).

**Comment by skurzhanskyi** [comment]
Thanks for noticing this, we'll fix the doc.

**Comment by Chunngai** [comment]
Ok. I also notice that `--pretrain_folder` is missed in the 2nd and the 3rd stage in the doc.

**Comment by Chunngai** [comment]
And `special_tokens_fix` is missed in the doc as mentioned in #128.
