### ISSUE TITLE
preprocessing limits

### ISSUE THREAD

**Issue by tonytan48** [grammarly/gector#13]
Hi,

    I am trying to reproduce the results for BEA19 shared task. May I know what kind of pre-training data you used for initial training? Also, it seems when I try to construct large preprocessed data from the errorify repository. I got stuck at around 800,000 pairs of parallel copora. May I know what pretraining corpora did you use for producing the roberta score?

![image](https://user-images.githubusercontent.com/10150598/86591763-c7837d80-bfc4-11ea-8574-4d3c9cfafdda.png)

**Comment by skurzhanskyi** [comment]
As mentioned in the paper, for initial training, we use synthetic data (w/o any filtering), preprocessed with our script. Indeed, the data is downloaded from the [errorify](https://github.com/awasthiabhijeet/PIE/tree/master/errorify) repository you wrote about. I guess the problem you have with preprocessing that your RAM is not enough. You can split the file into about 11 parts (800_000 rows each) and preprocess them separately.

**Comment by skurzhanskyi** [comment]
Hi @tonytan48 
Did I answer your question in the message above?

**Comment by tonytan48** [comment]
Thank you for the answer. I tried to use a seperate machine and monitered the ram usage. Seems it still somewhat stucked at 800,000 even though the ram usage is low. But separating and process them individually works.
