### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Zecheng-Tang** [grammarly/gector#134]
Hi, when I use pretrained model (bert) to inference, an error occurs. My script and error is listed below. Could you give me some suggestions ?

![图片](https://user-images.githubusercontent.com/59752775/139025957-570eea91-d24c-4ae2-9f45-14bc65408041.png)

![图片](https://user-images.githubusercontent.com/59752775/139025536-8acdf0a0-54ff-4935-81e0-a33cbac72e54.png)

**Comment by skurzhanskyi** [comment]
We don't have the answer and the moment 🤔 
From the error message, it looks like the error appears at the post-processing step (applying the predicted labels). It may be related to some corner cases with input data.
Could you share the particular sentence, which causes the error?

**Comment by alan-ai-learner** [comment]
> 

facing same error did you guys @skurzhanskyi @Zecheng-Tang  solve it

**Comment by Zecheng-Tang** [comment]
> We don't have the answer and the moment 🤔 From the error message, it looks like the error appears at the post-processing step (applying the predicted labels). It may be related to some corner cases with input data. Could you share the particular sentence, which causes the error?

Sorry for my late reply ！I will start a new issue to discuss this problem with you later.

**Comment by Zecheng-Tang** [comment]
> > 
> 
> facing same error did you guys @skurzhanskyi @Zecheng-Tang solve it

Did you pass a long sentence to the model? I remember I fed a long sentence into the model(but shorter than --max_len) and get an error.

**Comment by alan-ai-learner** [comment]
> 

Seems like the, the error is due to the sentence length, i make  some changes in the helpers.py file  and it worked!
``` Python
if label == "":
    try:
      del target_tokens[target_pos]
      shift_idx -= 1
    except:
      continue
```

**Comment by Zecheng-Tang** [comment]
> > 
> 
> Seems like error is due to the sentence length, i made some changes in the helpers.py file and it worked!
> 
> ```python
> if label == "":
>     try:
>       del target_tokens[target_pos]
>       shift_idx -= 1
>     except:
>       continue
> ```

That's it! I will try it later! Thank you very much.
