### ISSUE TITLE
Why not try a new model? Like ELECTRA ...

### ISSUE THREAD

**Issue by Yang-HangWA** [grammarly/gector#135]
I think there are some new model developments that can be added to this work. :smile:

**Comment by skurzhanskyi** [comment]
This repository implements the models reported in the [GECToR paper](https://aclanthology.org/2020.bea-1.16/).
If you want to train models with other transformer pretraining you need to change the code [here](https://github.com/grammarly/gector/blob/master/train.py#L301) and [here](https://github.com/grammarly/gector/blob/91edfcc177600bad145a98c3b7a64e3ddb12475d/utils/helpers.py#L187).

**Comment by Yang-HangWA** [comment]
@skurzhanskyi  Thanks for your reply. I mean there may be other models that do better.  Anyway, thank you. I will try this later.
