### ISSUE TITLE
Format of SOURCE and TARGET

### ISSUE THREAD

**Issue by justinpeh97** [grammarly/gector#136]
Hi, may I check what is the required format for SOURCE and TARGET?

For instance, would SOURCE be a .txt file with all the incorrect sentences, and then TARGET a .txt with all the correct sentences?

Otherwise, what format should SOURCE and TARGET be in?

I cannot seem to find any documentation on this anywhere.

**Comment by skurzhanskyi** [comment]
Yes, this is correct. Usually source = model input, target = model desired output.

**Comment by justinpeh97** [comment]
Thank you so much for the help. Managed to get it to work.
