### ISSUE TITLE
Problems using pretrained weights

### ISSUE THREAD

**Issue by justinpeh97** [grammarly/gector#137]
Dear @skurzhanskyi  and friends, 

I ran into some problems during training with pretrained weights.

Running without pretrained weights work fine.
![image](https://user-images.githubusercontent.com/68331483/140907450-f23bf8db-dfb6-4ae7-a4b0-1ea7153b2b7f.png)

Specifying transformer_model, pretrain_folder and pretrain led to some problems.

![image](https://user-images.githubusercontent.com/68331483/140907598-a62da0c6-9417-4bcd-831b-674fbdea5f23.png)

As per suggested in another issue, I added in vocab_path data/output_vocabulary [from gector repo] as well as other parameters, but this led to another issue

![image](https://user-images.githubusercontent.com/68331483/140907900-5ff9f6d0-1db2-47b0-9937-a96a7375b7ef.png)

Would appreciate any help provided, thanks alot!

**Comment by skurzhanskyi** [comment]
Hi @justinpeh97
Does this problem appear only with XLNet or with other pretrained models too?

**Comment by justinpeh97** [comment]
@skurzhanskyi  this problem appears with other models too.

What I have done is:
Clone the github gector repo
Call preprocess_data.py on my train set and dev set, producing train.txt and dev.txt 
Download pretrained models from the current repo and put into pretrained_weights

Do you have any advice on what I should have done differently?

**Comment by skurzhanskyi** [comment]
I tried to reproduce your case, but I have no errors.
Did you run the `pip install -r requirements.txt` command?
Otherwise, the problem may be data-related 🤔

**Comment by skurzhanskyi** [comment]
We also updated the code recently. Make sure you're using the latest version.

**Comment by justinpeh97** [comment]
> I tried to reproduce your case, but I have no errors. Did you run the `pip install -r requirements.txt` command? Otherwise, the problem may be data-related 🤔

@skurzhanskyi  Thank you for your reply. I will definitely try to process the data and try the model again.
