### ISSUE TITLE
Could we delete the token '$START' ?

### ISSUE THREAD

**Issue by spurscoder** [grammarly/gector#14]
Hi, thanks for your wonderful codes.

But, I wonder if we can delete the token '$START', when preprocessing the dataset. Because I found this token didn't make a lot of sense.

**Comment by AutoTemp** [comment]
Some '$START's are tagged as '$APPEND_xxx', so you better keep it.
(in my understanding)

**Comment by spurscoder** [comment]
oh, I know it, thank you.

**Comment by komelianchuk** [comment]
Yes, we added `$START` token in order to be able to insert words at the beginning of the sentence.
