### ISSUE TITLE
Number of iterations while training

### ISSUE THREAD

**Issue by LeonhardEulerr** [grammarly/gector#140]
Hello, I have a quite big corpus consisting of around 20M sentences. I am trying to figure out what parameters, if any, have control over number of iterations while training the model. 

![image](https://user-images.githubusercontent.com/73944828/142608859-e71d4f60-030b-433b-9b23-bb289563a7c3.png)

I was able to figure out that the greater dataset the more iterations will be done which is reasonable but I cant find anything about how to control that in the code. Is it poissible?

I also see that when it iterates, it does around 1000 iterations and pause for couple of secods then continues. Is there any way to increase it/s as it is not the same in every run of training?

**Comment by skurzhanskyi** [comment]
We have `--n_epoch` parameter. So the training time is proportional to the size of the dataset.

**Comment by skurzhanskyi** [comment]
Number of iteration per epoch = number of examples in the dataset / batch size
