### ISSUE TITLE
Some questions about reproduce

### ISSUE THREAD

**Issue by AC-god** [grammarly/gector#145]
Hello,

We are undergraduate students in Taiwan, since we appreciate your implementation very much, we would like to reproduce your paper “GECToR – Grammatical Error Correction: Tag, Not Rewrite” as a NLP course project, however, we encounter some problems.

We have followed all the instructions of the requirement.txt, so the version shouldn’t be a problem.

Here is our question:

We key in an instruction:"python train.py --train_set ./fce/m2/fce.train.gold.bea19.m2 --dev_set ./fce/m2/fce.dev.gold.bea19.m2 --model_dir ./bert"

And we expect this will produce some results, but the console shows like the below picture.

 
![image](https://user-images.githubusercontent.com/51225338/147218173-bb848e39-ae1e-4216-8584-f7e36bdc7606.png)
![image](https://user-images.githubusercontent.com/51225338/147218192-2ce9ec5a-fe4e-4c21-a1e3-7dc0ca8b5842.png)

 

We have no idea why “labels” and “loss” don’t exist.

Is there any suggestion or give us all the instructions from stage1 to stage3?

Thank you very much!

**Comment by skurzhanskyi** [comment]
Hello, 
As mentioned in README, you need to convert parallel data (src and trg files) to a particular format to use it for training:
https://github.com/grammarly/gector#datasets
