### ISSUE TITLE
Loading TST-FINAL Model

### ISSUE THREAD

**Issue by yassinekdi** [grammarly/gector#147]
Thank you for the amazing work with the Text Simplification! I'm just stuck at loading the weights (in the th model). I could just get the dictionary ( `torch.load(yourmodel.th)` ) but I couldn't use the loaded weights in any model. I tried use huggingface models (Roberta) but it's not working. I read you used AllenNLP in your papers. I tried AllenNLP models but still couldn't load it. Any Idea ?
Thank you :)

**Comment by skurzhanskyi** [comment]
Hi @yassinekdi 
Did you find a solution?

**Comment by yassinekdi** [comment]
Hi,Actually I just ended up using the python command (python predict.py etc.). Since I just wanted to take a look on the results that was enough :) 
    Le jeudi 30 décembre 2021, 12:47:11 UTC+1, Alex Skurzhanskyi ***@***.***> a écrit :  
 
 


Hi @yassinekdi
Did you find a solution?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
