### ISSUE TITLE
Questions about processing synthetic data

### ISSUE THREAD

**Issue by liangnn17** [grammarly/gector#154]
Hi,

I noticed that the tokenization method in PIE data is different from the nucle and fce data you used. I'm wondering whether I need to  detokenize the PIE data and use spacy to do tokenization on my own.

Looking forward to your advice!

**Comment by mina1460** [comment]
no, you don't need to tokenize it yourself. You can use the script they provided for preprocessing in order to get the data ready in a compatible format for gector.
