### ISSUE TITLE
Module Not found error 

### ISSUE THREAD

**Issue by ayush-1701** [grammarly/gector#156]
ModuleNotFoundError: No module named 'allennlp.data.iterators'

Giving this error,

**Comment by Arvinth-s** [comment]
Hey @ayush-1701, did you install the requirements? Did you get any error while executing ```pip install -r requirements.txt``` ?

**Comment by mina1460** [comment]
you need to install allennlp 0.8.4 as newer versions will not work (some modules were removed).
