### ISSUE TITLE
Discard the last label when predicting?

### ISSUE THREAD

**Issue by AutoTemp** [grammarly/gector#16]
In the function postprocess_batch of gec_model.py, 
'for i in range(length):' seems discard the last label in idxs, since len(idxs) == len(tokens)+1 == length+1
idxs is the labels for [$START]+tokens

**Comment by komelianchuk** [comment]
Great catch! Thank you! 
We will fix this issue soon.

**Comment by komelianchuk** [comment]
Fixed in #18
