### ISSUE TITLE
Could you release a normal version based on Git tags for a wider audience to download and use?

### ISSUE THREAD

**Issue by chengzhijin** [grammarly/gector#161]
First of all, thanks a lot for your excellent work on GECToR.
I am an algorithm engineer from a technology company.  Part of my project involves grammatical error correction. It would be appreciated if you could release a normal version based on Git tags for more follower to  cite, download and use. 
Looking forward to your reply.

**Comment by skurzhanskyi** [comment]
Hi @chengzhijin 
Could you please specify your idea in more detail? What tags do you suggest adding?

**Comment by chengzhijin** [comment]
Thanks for your reply.
Adding tags means publicize your release for production-ready with a normal version, e.g., v1.0.0
This can be done in just a few steps：

1. On GitHub.com, navigate to the main page of the repository.
2. To the right of the list of files, click Releases.
3. Click Draft a new release.
4. Click Choose a tag, type a version number for your release, and press Enter. Alternatively, select an existing tag.
5. If you are creating a new tag, click Create new tag.
6. If you have created a new tag, use the drop-down menu to select the branch that contains the project you want to release.
...
8.  Type a title and description for your release. If you @mention any GitHub users in the description, the published release will include a Contributors section with an avatar list of all the mentioned users. Alternatively, you can automatically generate your release notes by clicking Generate release notes.
...
12. If you're ready to publicize your release, click Publish release. To work on the release later, click Save draft.


More detail could be found as the following link.
[https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository](url)

**Comment by chengzhijin** [comment]
Also, adding tags could help manage the versions of your release or pre-release.
@skurzhanskyi , could you please consider going for a release version?
Thanks.

**Comment by skurzhanskyi** [comment]
Thank you, @chengzhijin! We'll discuss it with a team

**Comment by skurzhanskyi** [comment]
As it's a research repository and we do not have plans to add huge updates, we decided not to add tags.
