### ISSUE TITLE
Predict problem

### ISSUE THREAD

**Issue by CoderBinGe** [grammarly/gector#165]
Hi, Thanks for your work. I encountered a strange problem when predicting(run predict.py directly via PyCharm), as shown below：

![image](https://user-images.githubusercontent.com/26380524/187337804-280222e2-c3bc-4e82-aa48-48c1fb250b13.png)

I would appreciate if you could give some advice!

**Comment by skurzhanskyi** [comment]
Hi
What command did you use?

**Comment by CoderBinGe** [comment]
> Hi What command did you use?

Hi, It is ok when run with the following command:

`python predict.py --model_path plm/roberta_1_gectorv2.th --vocab_path data/output_vocabulary/ --input_file test.txt  --output_file result.txt --transformer_model roberta --special_tokens_fix 1`

But when I set default values for these parameters(part of screenshot below) and run predict.py directly with PyCharm, I get the strange error in the screenshot above.

![image](https://user-images.githubusercontent.com/26380524/187570380-bac77822-8885-4006-88bd-0c68a2b2d662.png)
