### ISSUE TITLE
The size of raw dataset is 0

### ISSUE THREAD

**Issue by aimanmutasem** [grammarly/gector#17]
Thank you for the magnificent article and code. I'm sorry if my question is looked silly. 

I have downloaded just one dataset (fce.train.gold.bea19.m2, Dev, and test) and moved files to the data directory, then started training I get the error 'The size of raw dataset is 0'.

My questions: 

Is it required to rename any dataset files before moving it to the data directory? including parallel and synthetic datasets. 

Also, can I run all the training process in a single GPU?

**Comment by Jason3900** [comment]
There's a preprocessing script in `./utils` directory named "preprocess_data.py". you should use it to preprocess with your raw corpus, and feed the preprocessed data to the model.

**Comment by aimanmutasem** [comment]
Thank you Mr. @Jason3900  for your response. 

Excuse me, 'python utils/preprocess_data.py -s SOURCE -t TARGET -o OUTPUT_FILE' , but I'm still confused. Mean, I have to convert (.m2) file into another Source and Target fills. For example, python utils/preprocess_data.py -s SOURCE.txt -t TARGET.txt -o OUTPUT_FILE.txt

Usually, I uploaded the training data as one file with two columns SRC and TRG.

**Comment by skurzhanskyi** [comment]
That's just the format we use for preprocessing. Parallel files format is used in various NLP tasks.

**Comment by aimanmutasem** [comment]
I have to pass the corpus rows as:

utils/preprocess_data.py -s SOURCE.txt -t TARGET.txt -o OUTPUT_FILE.txt

Right?

**Comment by skurzhanskyi** [comment]
Yes, from m2 file you can generate SOURCE.txt and TARGET.txt. `OUTPUT_FILE.txt` is the name of the file you get after preprocessing.

**Comment by aimanmutasem** [comment]
Excuse me, Sir, @skurzhanskyi  I'm back again
I got this error :

```
Traceback (most recent call last):
  File "utils/preprocess_data.py", line 488, in <module>
    main(args)
  File "utils/preprocess_data.py", line 469, in main
    convert_data_from_raw_files(args.source, args.target, args.output_file, args.chunk_size)
  File "utils/preprocess_data.py", line 330, in convert_data_from_raw_files
    source_data, target_data = read_parallel_lines(source_file, target_file)
  File "/home/aiman/gector-master/utils/helpers.py", line 141, in read_parallel_lines
    assert len(lines1) == len(lines2)
AssertionError
```

**Comment by skurzhanskyi** [comment]
As the error claims, the number of rows in source and target files is different, which should not be the case for parallel format.

**Comment by aimanmutasem** [comment]
I have checked that manually before, each file has 2659 lines.  but the size of files is different 206 and 208 KB.

**Comment by skurzhanskyi** [comment]
`assert len(lines1) == len(lines2)` checks whether the number of lines in source and target files is equal. Please check the number of lines/rows again.
