### ISSUE TITLE
Conversion from m2 to parallel

### ISSUE THREAD

**Issue by Chunngai** [grammarly/gector#179]
Hello! 

How did you convert M2 data to source-target parallel pairs for stage 2 & 3? You mentioned the [edit_creator.py](https://github.com/nusnlp/m2scorer/blob/master/scripts/edit_creator.py) script in #177 . Did you use this script for conversion? Or did you use another script, such as the one provided in the BEA2019 website?

Additionally, how did you handle M2 data with more than 1 annotators? Did you keep all or only use the annotations of the first annotator?

Thanks!

**Comment by Lj4040** [comment]
@Chunngai Hello!May I ask if you have solved this problem? If so, could you tell me the solution。

**Comment by skurzhanskyi** [comment]
We used something like [M2Convertor](https://github.com/Jason3900/M2Convertor), as mentioned in other issues.

**Comment by Chunngai** [comment]
@skurzhanskyi Got it. Thanks a lot!

**Comment by Chunngai** [comment]
@Lj4040 Has the answer from the author helped you, mate?

**Comment by Lj4040** [comment]
@Chunngai @skurzhanskyi  I really appreciate your help and answer, thank you for your reply,
