### ISSUE TITLE
What is special_tokens_fix doing?

### ISSUE THREAD

**Issue by suttergustavo** [grammarly/gector#183]
I understand that the special_tokens_fix is adding the $START token to the vocabulary, but can someone explain why we only do that for the RoBERTa model?

**Comment by skurzhanskyi** [comment]
This is just a setup in which the model was trained.

**Comment by suttergustavo** [comment]
I see, but training from scratch is there a difference between using it or not? My question is basically what to do if I want to try a new Transformer backbone, should I use it or not?

**Comment by skurzhanskyi** [comment]
Yes, I would rather train it using `special_tokens_fix` to avoid splitting it into the subwords.

**Comment by suttergustavo** [comment]
Makes sense, thanks very much for the answers!
