### ISSUE TITLE
I have some Issue with pakage version and this how it fix it

### ISSUE THREAD

**Issue by Nghiauet** [grammarly/gector#194]
1. sklearn 
version scikit-learn==0.20.0 deprecated 
=> Solved by 
`pip install scikit-learn==0.22.2`
2. Error with pytoch package
Error message
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
=> solved 
`pip install torch==1.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
`

**Comment by Jason3900** [comment]
Maybe you need a newer version of cuda, you can try install pytorch with cuda 11.7.

**Comment by Nghiauet** [comment]
> Maybe you need a newer version of cuda, you can try install pytorch with cuda 11.7.

I already updated the cuda version but it dont work. Only install new pytorch version fix that problem
