### ISSUE TITLE
How did you decide which type of token-level transformations to include in the edit space?

### ISSUE THREAD

**Issue by OscarWang114** [grammarly/gector#21]
Hi, thanks for the amazing paper and recording at BEA 15, ACL 2020!

I was wondering how did you decide which type of token-level transformations to include in the edit space? For example, the 1167 token-dependent APPEND and 3802 REPLACE. Is it a dataset-driven process, e.g. determined by ranking the most frequent transformations in CoNLL-2014 and selecting the top 5000?

Many thanks in advance!

**Comment by skurzhanskyi** [comment]
Hi @OscarWang114 
Yes, you're right. It's a dataset-driven process. As far as I remember we chose the top 5000 transforms on the united academic dataset (CoNLL-2014, Lang8, W&I+LOCNESS, FCE) and then used them on all stages.

**Comment by OscarWang114** [comment]
@skurzhanskyi Got it! Thanks for the reply 😄
