### ISSUE TITLE
Can i resume training from where i left off by loading the last state of the model?

### ISSUE THREAD

**Issue by shikha10799** [grammarly/gector#24]
I want to confirm what does the below code actually do?( load the state of the model which we pass to the pretrain argument).Also a snapshot of the model after each epoch is stored in the model dir,therefore can we stop the pretraining in between and then pick again from where we left off by using the below code to load the last snapshot of the model being pretrained.(for the purpose of pretraining in a non continuous manner taking some breaks)

` if args.pretrain:
        model.load_state_dict(torch.load(os.path.join(args.pretrain_folder, args.pretrain + '.th')))`

if i am right than which file should i pass to the "pretrain" argument above in order to continue training?
options - model_state_epoch.th OR training_state_epoch.th

**Comment by shikha10799** [comment]
please forgive me if my question is too naive.

**Comment by shikha10799** [comment]
let me clear that I have taken the above code section from line 140 -141 of the gector/train.py file.

**Comment by skurzhanskyi** [comment]
Yes, you're right that the following code loads the model from the given checkpoint, and you can resume training. That's how we have three stages. Regarding your question about `model_state_epoch.th` and `training_state_epoch.th`:
`model_state_epoch.th` stores the model, while `training_state_epoch.th` stores training data (metric_tracker, optimizer etc).
You can check it using `torch.load`. So you need to pass `model_state_epoch.th` as a `pretrain` parameter.
More information about storing you can find in `AllenNLP` library.

**Comment by shikha10799** [comment]
Ok I got it.Thanks for the support and patience.👍
