### ISSUE TITLE
xlnet_base_cased

### ISSUE THREAD

**Issue by Ysmita** [grammarly/gector#25]
Hi...!
When I run predict.py using transfomer as xlnet, internally 3 files get downloaded. Are those 3 files xlnet_base_cased model ? If so, then I have downloaded the cased model. Now where in the code do I need to change such that it loads the model from the folder containing the downloaded model ?

**Comment by skurzhanskyi** [comment]
Yes, for XLNet model we use `xlnet-base-cased` weights:
https://github.com/grammarly/gector/blob/06d08b2876a128a7a0939dd09fca54e0fc9081ef/utils/helpers.py#L202-L203
You downloaded model pertaining weights and tokenizer data (e.g. vocabulary). 
You can use custom weights using `pretrain_folder` and `pretrain` parameters, as it was mentioned in https://github.com/grammarly/gector/issues/24

**Comment by Jason3900** [comment]
@Ysmita 
Hi!
I think there's also another way. In `./gector/gec_model.py`, you can modify line 173 and line 186 to `pretrained_model=os.path.join(<YOUR_DOWNLOADED_MODEL_DIR's parent dir>,weigths_name)`. Then every time you load the model for prediction, it will load the model from the local path. For training, you can modify `./train.py` line 29 and line 42 to do the same thing.
