### ISSUE TITLE
Can't train the model

### ISSUE THREAD

**Issue by SuHe36** [grammarly/gector#28]
I preprocess the data as described in README, the preprocessed train dataset as follows:

- $STARTSEPL|||SEPR$KEEP DecemberSEPL|||SEPR$KEEP 12thSEPL|||SEPR$KEEP
- $STARTSEPL|||SEPR$KEEP PrincipalSEPL|||SEPR$KEEP mr.SEPL|||SEPR$KEEP robertsonSEPL|||SEPR$KEEP

I think the preprocess phrase is right.

Then I use the following script, run.sh,  to train the model:
`CUDA_VISIBLE_DEVICES=0 python train.py --train_set ./data/fce-train.pre \`
`--dev_set ./data/conll-dev.pre \`
`--model_dir ./model \`
`--transformer_model bert`

but it reported an error, as follows:
`18545it [00:01, 9993.01it/s]`
`Data is loaded`
`run.sh: line 4: 731383 Segmentation fault     (core dumped) CUDA_VISIBLE_DEVICES=0 python train.py --train_set ./data/fce-train.pre --dev_set ./data/conll-dev.pre --model_dir ./model --transformer_model bert  `

my environment is Cuda 9.2, pytorch1.3.1.
does anyone know how to solve this problem or are there any problems with my process?

**Comment by SuHe36** [comment]
When I upgrade the environment to torch1.4,  and solved this problem.

**Comment by Jason3900** [comment]
I've met this problem before. It's transformers/pytorch/scipy version related. I use transformers installed from source and `torch=1.5 cuda=10.1 scipy=1.3.2`, then the problem is solved.
