### ISSUE TITLE
How to reproduce the XLNet 72.4 f0.5-score

### ISSUE THREAD

**Issue by HelenaHlz** [grammarly/gector#29]
I use the command 

"python predict.py --model_path pretained_model/xlnet_0_gector.th \
 --input_file ABCN.bea19.test.orig \
 --output_file bea19_test.txt --transformer_model xlnet --special_tokens_fix=0"
Then I submit the result to the CodaLab. It shows the Span-level correction F0.5 is 65.35.
 
Do I use the correct command? If I wanna get 72.4, how should I set the predict command?

**Comment by tonytan48** [comment]
I guess in this case, you can refer to Table.11 in the appendix and use the corresponding parameter. For XLNet is --additional_confidence 0.35 and --min_error_probability=0.66.

**Comment by HelenaHlz** [comment]
> I guess in this case, you can refer to Table.11 in the appendix and use the corresponding parameter. For XLNet is --additional_confidence 0.35 and --min_error_probability=0.66.

Thanks! I set these two hyperparameters and receive 72.46.
