### ISSUE TITLE
size mismatch for text_field_embedder.token_embedder_bert.bert_model.word_embedding.weight

### ISSUE THREAD

**Issue by AutoTemp** [grammarly/gector#3]
1. By 
```
python predict.py --model_path xlnet_0_gector.th --vocab_path data/output_vocabulary/ --input_file xxx--output_file xxx --transformer_model xlnet
```
I get
```
size mismatch for text_field_embedder.token_embedder_bert.bert_model.word_embedding.weight: copying a param with shape torch.Size([32000, 768]) from checkpoint, the shape in current model is torch.Size([32006, 768]).
```
But when I use Roberta(which is default setting), the run is ok.
Thanks!

**Comment by skurzhanskyi** [comment]
For XLNet and BERT models you need additionally use `--special_tokens_fix=0` parameter, as it is mentioned in `predict.py`.

**Comment by AutoTemp** [comment]
> To reproduce the results of XLNet and BERT, you should additionally use `--special_tokens_fix=0` parameter, as it is mentioned in `predict.py`.

Thanks! Now I can completely reproduce the results.

**Comment by shikha10799** [comment]
@AutoTemp  how much time did it took for the predict.py script to complete execution in yours case?
