### ISSUE TITLE
Train and Dev Set for COLL2014 for Stage II, III

### ISSUE THREAD

**Issue by MichaelCaohn** [grammarly/gector#30]
HI!

I have seen the paper have mentioned the lang8, face, nucle, and wi+locness have been used for stage II and stage III.
![image](https://user-images.githubusercontent.com/22003919/88267051-d4ada580-cd02-11ea-895f-4d34bb526a38.png)
I believe this should be the case for BEA2019 test cases. 

For the case of COLL2014, do we still use lang8, face, nucle and wi+locness for stage II, and wi+locness for stage III as well? COLL2014 dataset is only involved in the final testing?

**Comment by komelianchuk** [comment]
Hi!
`do we still use lang8, face, nucle and wi+locness for stage II, and wi+locness for stage III as well?`
yes

`COLL2014 dataset is only involved in the final testing?`
We used only the training part of NUCLE data for training the model during stage2. So CoNLL2014 (test) was used only for evaluation.

**Comment by MichaelCaohn** [comment]
Thank you very much for the kind reply. It solved my problem.
