### ISSUE TITLE
Any other embeddings? 

### ISSUE THREAD

**Issue by creeston** [grammarly/gector#32]
Hi! 

I am wondering, is there is a easy way to make use of other word embeddings? Mostly intested in those with OOV (out of vocabulary) feature, like Fasttext, or randomly intialized character-level embeddings. Or only transformer-embeddings are supported?

The reason is that I am trying to use your model for typo-correction task (which is a subtask of grammar correction task), so I have a lot of OOV-word in my dataset and I think that using character-level embeddings (or embeddings with OOV) may increase accuracy of model.

**Comment by komelianchuk** [comment]
Hi!

We've tried other from transformers embeddings at the very beginning of this research and they showed worse results.
The current implementation is not supporting adding other embeddings, but you can tweak our code.
Just want to add that transformers use BPE tokenization, so I think they should cover OOV words relatively well.

**Comment by creeston** [comment]
> Hi!
> 
> We've tried other from transformers embeddings at the very beginning of this research and they showed worse results.
> The current implementation is not supporting adding other embeddings, but you can tweak our code.
> Just want to add that transformers use BPE tokenization, so I think they should cover OOV words relatively well.

Ok, understood, thanks a lot for the reply! 👍
