### ISSUE TITLE
Is there any way to train other than english?

### ISSUE THREAD

**Issue by virgulvirgul** [grammarly/gector#35]
Can I use `bert-base-multilingual-cased` or another multilingual model and how?

**Comment by komelianchuk** [comment]
Hi, @virgulvirgul !

I think it is not easy to apply this approach to other languages.
The most complex thing that you need to do is developing custom language-specific tags for the selected language and modifying the preprocessing script. 
Adding support for other transformer models should be much easier compared to the aforementioned step.

**Comment by virgulvirgul** [comment]
Thank you for your answer. 
Could you please show a way or example to add other transformer model, like huggingface models?

**Comment by skurzhanskyi** [comment]
You can edit code here https://github.com/grammarly/gector/blob/master/utils/helpers.py#L181-L203 to specify alias to huggingface models.
