### ISSUE TITLE
How to run inference with pretrained models?

### ISSUE THREAD

**Issue by davidefiocco** [grammarly/gector#36]
I am trying to run gector using BERT, and I am likely missing something very trivial... to do so

- I cloned this repo
- I installed all requirements in a dedicated Python 3.7 conda environment called "gector"
- I downloaded the BERT model from https://grammarly-nlp-data-public.s3.amazonaws.com/gector/bert_0_gector.th
- I took from https://www.cl.cam.ac.uk/research/nl/bea2019st/data/wi+locness_v2.1.bea19.tar.gz the file ABCN.test.bea19.orig that I thought to use as input file.

I ran inference by firing on bash

`python predict.py --model_path .\bert_0_gector.th --vocab_path .\data\output_vocabulary\ --input_file .\ABCN.test.bea19.orig --output_file foo`

Execution crashes with:

```
I0728 17:10:37.239058 26000 file_utils.py:40] PyTorch version 1.3.0 available.
I0728 17:10:38.438563 26000 vocabulary.py:306] Loading token dictionary from .\data\output_vocabulary\.
I0728 17:10:39.341149 26000 tokenization_utils.py:398] loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-vocab.json from cache at C:\Users\davide.fiocco\.cache\torch\transformers\d0c5776499adc1ded22493fae699da0971c1ee4c2587111707a4d177d20257a2.ef00af9e673c7160b4d41cfda1f48c5f4cba57d5142754525572a846a1ab1b9b
I0728 17:10:39.342149 26000 tokenization_utils.py:398] loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-merges.txt from cache at C:\Users\davide.fiocco\.cache\torch\transformers\b35e7cd126cd4229a746b5d5c29a749e8e84438b14bcdb575950584fe33207e8.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
I0728 17:10:39.432337 26000 tokenization_utils.py:548] Adding $START to the vocabulary
I0728 17:10:39.908694 26000 configuration_utils.py:160] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-config.json from cache at C:\Users\davide.fiocco\.cache\torch\transformers\e1a2a406b5a05063c31f4dfdee7608986ba7c6393f7f79db5e69dcd197208534.117c81977c5979de8c088352e74ec6e70f5c66096c28b61d3c50101609b39690
I0728 17:10:39.909693 26000 configuration_utils.py:177] Model config {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 1,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 1,
  "use_bfloat16": false,
  "vocab_size": 50265
}

I0728 17:10:40.361510 26000 modeling_utils.py:401] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-pytorch_model.bin from cache at C:\Users\davide.fiocco\.cache\torch\transformers\228756ed15b6d200d7cb45aaef08c087e2706f54cb912863d2efe07c89584eb7.49b88ba7ec2c26a7558dda98ca3884c3b80fa31cf43a1b1f23aef3ff81ba344e
E0728 17:10:44.443636 26000 vocabulary.py:632] Namespace: d_tags
E0728 17:10:44.444651 26000 vocabulary.py:633] Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "C:\Users\davide.fiocco\Projects\gector\gector\gec_model.py", line 89, in __init__
    confidence=self.confidence
  File "C:\Users\davide.fiocco\Projects\gector\gector\seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "C:\Users\davide.fiocco\Anaconda3\envs\gector\lib\site-packages\allennlp\data\vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
```
There's quite a few things that I couldn't understand from the README file

1. Should I specify an existing output file?
2. Why does gector import RoBERTa if I have specified a pretrained BERT model?
3. Why the crash in the allennlp library?

Ultimately, I would like to:

- For an input sentence, see the transformation tags
- For an incorrect sentence, compute iteratively its corrected version

Thanks for any guidance on this...!

**Comment by komelianchuk** [comment]
Hi!
You also need to specify `transformer_model` and `special_tokens_fix` parameters. For BERT model they are `bert` and `0`.

**Comment by davidefiocco** [comment]
Thanks @komelianchuk!

I thus reran with 

    python predict.py --model_path . --vocab_path .\data\output_vocabulary\ --input_file .\ABCN.test.bea19.orig --output_file bar --transformer_model bert --special_tokens_fix 0

And BERT gets indeed loaded.

However, the run is still not successful:

I0729 10:03:16.222485 27056 file_utils.py:40] PyTorch version 1.3.0 available.
I0729 10:03:17.287333 27056 vocabulary.py:306] Loading token dictionary from .\data\output_vocabulary\.
I0729 10:03:17.780309 27056 tokenization_utils.py:398] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt from cache at C:\Users\davide.fiocco\.cache\torch\transformers\5e8a2b4893d13790ed4150ca1906be5f7a03d6c4ddf62296c383f6db42814db2.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1
I0729 10:03:18.371772 27056 configuration_utils.py:160] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json from cache at C:\Users\davide.fiocco\.cache\torch\transformers\b945b69218e98b3e2c95acf911789741307dec43c698d35fad11c1ae28bda352.9da767be51e1327499df13488672789394e2ca38b877837e52618a67d7002391
I0729 10:03:18.374763 27056 configuration_utils.py:177] Model config {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 28996
}

I0729 10:03:18.830879 27056 modeling_utils.py:401] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin from cache at C:\Users\davide.fiocco\.cache\torch\transformers\35d8b9d36faaf46728a0192d82bf7d00137490cd6074e8500778afed552a67e5.3fadbea36527ae472139fe84cddaa65454d7429f12d543d80bfc3ad70de55ac2
E0729 10:03:20.537523 27056 vocabulary.py:632] Namespace: d_tags
E0729 10:03:20.537523 27056 vocabulary.py:633] Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "C:\Users\davide.fiocco\Projects\gector\gector\gec_model.py", line 89, in __init__
    confidence=self.confidence
  File "C:\Users\davide.fiocco\Projects\gector\gector\seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "C:\Users\davide.fiocco\Anaconda3\envs\gector\lib\site-packages\allennlp\data\vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'

    python predict.py --model_path . --vocab_path .\data\output_vocabulary\ --input_file .\ABCN.test.bea19.orig --output_file bar --transformer_model bert --special_tokens_fix 0

And BERT gets indeed loaded.

However, the run is still not successful:

I0729 10:03:16.222485 27056 file_utils.py:40] PyTorch version 1.3.0 available.
I0729 10:03:17.287333 27056 vocabulary.py:306] Loading token dictionary from .\data\output_vocabulary\.
I0729 10:03:17.780309 27056 tokenization_utils.py:398] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt from cache at C:\Users\davide.fiocco\.cache\torch\transformers\5e8a2b4893d13790ed4150ca1906be5f7a03d6c4ddf62296c383f6db42814db2.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1
I0729 10:03:18.371772 27056 configuration_utils.py:160] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json from cache at C:\Users\davide.fiocco\.cache\torch\transformers\b945b69218e98b3e2c95acf911789741307dec43c698d35fad11c1ae28bda352.9da767be51e1327499df13488672789394e2ca38b877837e52618a67d7002391
I0729 10:03:18.374763 27056 configuration_utils.py:177] Model config {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 28996
}

I0729 10:03:18.830879 27056 modeling_utils.py:401] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin from cache at C:\Users\davide.fiocco\.cache\torch\transformers\35d8b9d36faaf46728a0192d82bf7d00137490cd6074e8500778afed552a67e5.3fadbea36527ae472139fe84cddaa65454d7429f12d543d80bfc3ad70de55ac2
E0729 10:03:20.537523 27056 vocabulary.py:632] Namespace: d_tags
E0729 10:03:20.537523 27056 vocabulary.py:633] Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "C:\Users\davide.fiocco\Projects\gector\gector\gec_model.py", line 89, in __init__
    confidence=self.confidence
  File "C:\Users\davide.fiocco\Projects\gector\gector\seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "C:\Users\davide.fiocco\Anaconda3\envs\gector\lib\site-packages\allennlp\data\vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'

**Comment by komelianchuk** [comment]
Hi. Just want to check: are you using allennlp==0.8.4?

**Comment by komelianchuk** [comment]
I'm wondering whether it could be `Windows` related issue.
We've never tried to run this code in `Windows`.

Can you try to run it in Linux/MacOS?

**Comment by davidefiocco** [comment]
Sorry to report @komelianchuk, but I have the same problem on a Linux VM:
 ```
python predict.py --model_path . --vocab_path ./data/output_vocabulary --input_file ./ABCN.test.bea19.orig --output_file bar --transformer_model bert --special_tokens_fix 0
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 213k/213k [00:00<00:00, 825kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 282kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 436M/436M [00:10<00:00, 40.2MB/s]
Namespace: d_tags
Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "/data/home/dfiocco/Projects/gector/gector/gec_model.py", line 89, in __init__
    confidence=self.confidence
  File "/data/home/dfiocco/Projects/gector/gector/seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "/data/anaconda/envs/gector/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
 ```

while 

```
uname -a
Linux DataScienceVM 4.15.0-1091-azure #101~16.04.1-Ubuntu SMP Fri Jun 26 01:14:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by komelianchuk** [comment]
I guess that something is wrong with `/data/output_vocabulary`. 
Please try to load the vocabulary from the console and check all properties of this vocab.
`vocab = Vocabulary.from_files(vocab_path)`

**Comment by skurzhanskyi** [comment]
Also, you didn't specify `--model_path` properly. It should be `.pt` file.

**Comment by davidefiocco** [comment]
Sorry @skurzhanskyi those in the python command were typos. My errors reproduce by specifying `model_path` correctly. I have updated the comments above to reflect this.

**Comment by skurzhanskyi** [comment]
Also as @komelianchuk suggested, I recommend you to check the vocabulary.
It looks like you overrode it (maybe you tried to train the model).

**Comment by davidefiocco** [comment]
@komelianchuk @skurzhanskyi thanks both!

I tried running on a Linux machine again, rebuilding (again) the environment from scratch, and things worked as intended!
I'll investigate further why this is not the case on Linux... maybe something related to end-of-line chars in the vocab file? I am not sure.

I leave the steps before to run `gector` on inference:

```
git clone https://github.com/grammarly/gector.git
cd gector
#create conda env
conda create -n gector python=3.7
conda activate gector
pip install torch===1.3.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt
# get model
wget https://grammarly-nlp-data-public.s3.amazonaws.com/gector/bert_0_gector.th
# get eval file and inflate
wget https://www.cl.cam.ac.uk/research/nl/bea2019st/data/wi+locness_v2.1.bea19.tar.gz
tar -xzvf wi+locness_v2.1.bea19.tar.gz
# run inference
python predict.py --model_path ./bert_0_gector.th --vocab_path ./data/output_vocabulary/ --input_file wi+locness/test/ABCN.test.bea19.orig  --output_file foo --transformer_model bert --special_tokens_fix 0
```

(can also file a PR, but maybe leaving the above here is enough)

**Comment by komelianchuk** [comment]
Great to hear!
