### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Seq2Labels 

### ISSUE THREAD

**Issue by vogiralshivani** [grammarly/gector#39]
Unable to resolve this issue observed while loading the pre trained xlnet_0_gector model

RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	size mismatch for tag_labels_projection_layer._module.weight: copying a param with shape torch.Size([5002, 768]) from checkpoint, the shape in current model is torch.Size([5482, 768]).
	size mismatch for tag_labels_projection_layer._module.bias: copying a param with shape torch.Size([5002]) from checkpoint, the shape in current model is torch.Size([5482]).

**Comment by komelianchuk** [comment]
Hi. It seems that you are trying to use other from `data/output_vocabulary` vocab which is not expected behavior for pre-trained models.

**Comment by vogiralshivani** [comment]
I want to extend the vocabulary on new data and retrain the xlnet_0_gector model. How should I go about doing this?

**Comment by komelianchuk** [comment]
Then you either should not use pre-trained gector models or modify model loading code and do not load projection layers.

**Comment by vogiralshivani** [comment]
If that's the case, what would you suggest that I do?

**Comment by komelianchuk** [comment]
I think retraining from scratch will be a more correct approach.
