### ISSUE TITLE
If I wanted to conduct an experiment on custom data - how do I go about it?

### ISSUE THREAD

**Issue by Chhokra** [grammarly/gector#40]
I wanted to test this architecture with custom pretraining and training set. As I'm seeing in the codebase there's a common training script. According to the paper the training was done in 3 steps. So is it correct to assume that the common script of "train.py" was run 3 times each time on the previous step snapshot?

**Comment by skurzhanskyi** [comment]
Yes, it's correct.

**Comment by Chhokra** [comment]
> Yes, it's correct.

For pretraining, do I need to include the parameter "transformer_model" along with the parameters given for pretraining stage [here](https://github.com/grammarly/gector/blob/master/docs/training_parameters.md)

**Comment by skurzhanskyi** [comment]
We need to provide the model name (`transformer_model`) all the time. You can check it in the code or just running the training with the weights from another model type.

**Comment by Chhokra** [comment]
> We need to provide the model name (`transformer_model`) all the time. You can check it in the code or just running the training with the weights from another model type.

What's the significance of "vocab_path"? If I'm trying to train on custom data will the "vocab_path" still remain the same? If not then perhaps do we need to process a new vocab_path for that data?

**Comment by skurzhanskyi** [comment]
Vocabulary is built automatically if `vocab_path` is not specified. Whether to preserve our vocabulary depends on your particular task.
The vocabulary that we are talking about is the output vocabulary. For each particular model, its own vocabulary is used (e.g., for XLNet, XLNet vocabulary is used).
