### ISSUE TITLE
state_dict mismatch when loading from pretrained?

### ISSUE THREAD

**Issue by sabetAI** [grammarly/gector#49]
I'm tying to fine-tune on my own dataset from the pretrained model you provide (bert_0_gector.pt), with the following training arguments:

```
python3 train.py --train_set data/train \
        --dev_set data/dev \
        --model_dir models \
        --batch_size 100 \
        --cold_steps_count 1 \
        --pretrain_folder models \
        --pretrain bert_0_gector \
        --n_epoch 20
```

and get the follwoing error:

```
WARNING:root:vocabulary serialization directory models/vocabulary is not empty
Data is loaded
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main(args)
  File "train.py", line 141, in main
    model.load_state_dict(torch.load(os.path.join(args.pretrain_folder, args.pretrain + '.th')))
  File "/h/asabet/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.word_embeddings.weight: copying a param with shape torch.Size([28996, 768]) from checkpoint, the shape in current model is torch.Size([50266, 768]).
	size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.position_embeddings.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([514, 768]).
	size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.token_type_embeddings.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([1, 768]).
	size mismatch for tag_labels_projection_layer._module.weight: copying a param with shape torch.Size([5002, 768]) from checkpoint, the shape in current model is torch.Size([1002, 768]).
	size mismatch for tag_labels_projection_layer._module.bias: copying a param with shape torch.Size([5002]) from checkpoint, the shape in current model is torch.Size([1002]).
```
why would a mismatch show up if I'm just trying to load from pretrained?

**Comment by skurzhanskyi** [comment]
It looks like you didn't provide the very basic parameter —  the model name (`--transformer_model `). 
It's not obvious from the pure weights what particular model you want to train.
Please check the previous issues and README before creating the issue.
The examples of training parameters you can find [here](https://github.com/grammarly/gector/blob/master/docs/training_parameters.md).

**Comment by sabetAI** [comment]
That's a good suggestion-- I should have mentioned I had already tried adding `--transformer_model bert`, and get the following:

```
WARNING:root:vocabulary serialization directory models/vocabulary is not empty
Data is loaded
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main(args)
  File "train.py", line 141, in main
    model.load_state_dict(torch.load(os.path.join(args.pretrain_folder, args.pretrain + '.th')))
  File "/h/asabet/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
        size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.word_embeddings.weight: copying a param with shape torch.Size([28996, 768]) from checkpoint, the shape in current model is torch.Size([28997, 768]).
        size mismatch for tag_labels_projection_layer._module.weight: copying a param with shape torch.Size([5002, 768]) from checkpoint, the shape in current model is torch.Size([1002, 768]).
        size mismatch for tag_labels_projection_layer._module.bias: copying a param with shape torch.Size([5002]) from checkpoint, the shape in current model is torch.Size([1002]).

```

What parameters was `bert_0_gector.pt` trained with that could be producing such an error?

**Comment by komelianchuk** [comment]
You have not specified another important parameter `special_tokens_fix=0`

**Comment by komelianchuk** [comment]
And you have not specified `vocab_path` which is needed if you are using pretrained models.

**Comment by WANG-Yuchen-Alice** [comment]
Hi, I tried to predict by the following command:
`python predict.py --model_path pre_trained_model/bert_0_gectorv2.th --vocab_path model_1102/vocabulary --input_file data/test_wrong.txt --output_file data/result_1101.txt --transformer_model bert --special_tokens_fix 0`

However, I get the similar error as follows:

Traceback (most recent call last):
  File "predict.py", line 128, in <module>
    main(args)
  File "predict.py", line 47, in main
    weigths=args.weights)
  File "/home/wangyuchen/gector/gector/gec_model.py", line 69, in __init__
    model.load_state_dict(torch.load(model_path), strict=False)
  File "/home/wangyuchen/anaconda3/envs/CS4248/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	size mismatch for tag_labels_projection_layer._module.weight: copying a param with shape torch.Size([5002, 768]) from checkpoint, the shape in current model is torch.Size([1002, 768]).
	size mismatch for tag_labels_projection_layer._module.bias: copying a param with shape torch.Size([5002]) from checkpoint, the shape in current model is torch.Size([1002]).

May I seek for help regarding this issue? Thank you very much!

**Comment by skurzhanskyi** [comment]
@WANG-Yuchen-Alice What vocabulary do you use? You should use `/data/output_vocabulary/` if you want to run pretrained models.

**Comment by WANG-Yuchen-Alice** [comment]
Thank you! I tried to train on pre-trained model in this way:
`python train.py --train_set data/train.txt --dev_set data/dev.txt --model_dir model_1104 --tune_bert 1 --skip_correct 1 --skip_complex 0 --max_len 50 --batch_size 64 --tag_strategy keep_one --cold_steps_count 0 --cold_lr 1e-3 --lr 1e-5 --predictor_dropout 0.0 --lowercase_tokens 0 --pieces_per_token 5 --vocab_path data/output_vocabulary --label_smoothing 0.0 --patience 0 --transformer_model bert --accumulation_size 2 --updates_per_epoch 0 --tn_prob 1 --tp_prob 1 --pretrain bert_0_gectorv2 --pretrain_folder pre_trained_model`
but also get the mis-match error.
<img width="953" alt="Screenshot 2021-11-04 at 10 59 17 AM" src="https://user-images.githubusercontent.com/45040630/140250539-d0d7395b-c6f0-4348-bc22-9031f93be361.png">

I have commented in another similar issue. Thank you very much and really appreciate your help!

**Comment by WANG-Yuchen-Alice** [comment]
Noted. Thank you very much!

**Comment by tkhabia** [comment]
I also try to run this in colab via
`python predict.py --model_path /content/gector/roberta_1_gectorv2.th --input_file input.txt --output_file out.txt --special_tokens_fix 0 --max_len 150 --transformer_model roberta --vocab_path /content/gector/data/output_vocabulary`
However I am also facing similar issue.
```
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "predict.py", line 128, in <module>
    main(args)
  File "predict.py", line 47, in main
    weigths=args.weights)
  File "/content/gector/gector/gec_model.py", line 69, in __init__
    model.load_state_dict(torch.load(model_path), strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.word_embeddings.weight: copying a param with shape torch.Size([50266, 768]) from checkpoint, the shape in current model is torch.Size([50265, 768]).
```

**Comment by skurzhanskyi** [comment]
@tkhabia For RoBERTa, you need to use `--special_tokens_fix 1` parameter.
