### ISSUE TITLE
Is it convenient to provide a  GEC model trained?

### ISSUE THREAD

**Issue by JiqiangLiu** [grammarly/gector#5]
Hi, Could you provide the GEC model that has trained? Thank you very much.

**Comment by skurzhanskyi** [comment]
The links for downloading GEC models provided at `Pretrained models` section:
https://github.com/grammarly/gector#pretrained-models

**Comment by JiqiangLiu** [comment]
@skurzhanskyi oh, I thought it was the pre-trained LM model and not GEC model. Thank you.

**Comment by skurzhanskyi** [comment]
Sure. In this paper, we do not use LM models or spellcheckers. All results achieved with pure models.
