### ISSUE TITLE
Installation error in allennlp==0.8.4 

### ISSUE THREAD

**Issue by jonaskratochvil** [grammarly/gector#51]
Hello,

I am running into error when installing gector requirement allennlp==0.8.4. More specifically, there seem to be an error when installing gevent library:

x86_64-linux-gnu-gcc: error: src/gevent/libev/corecext.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Is there some workaround this bug? The latest version of allennlp installs without problems but then I encounter dependency issues with gector.

Thank you,

Jonas

**Comment by skurzhanskyi** [comment]
Hey
I've just checked the installation on a working machine and everything looks fine for me.
Maybe you're missing system development libraries 
```sudo apt-get install libblas-dev libatlas-base-dev python3.6-dev
```
