### ISSUE TITLE
Extending functionalities: Adding Contextual Spell Check/Correction capabilities

### ISSUE THREAD

**Issue by brijesh-6899** [grammarly/gector#52]
Hi,

I wanted your suggestions for adding extra functionalities, 

1. adding Contextual, Academic Spell Correction along with Grammar Error Suggestions.

2. How can I approach the grammar error correction in Academic (mainly K-12 context) domain, where textual data may contain equations, mathematical encodings, latex, HTML (tables, lists etc), XML and stuff?

Could you help me with this, In terms of feasibility and approach?

**Comment by skurzhanskyi** [comment]
The data we used for training is definitely not suitable for equations, mathematical encodings, latex, HTML (tables, lists, etc), XML. The easiest way not to break these elements is to select them and not to pass into the model.
Regarding Contextual, Academic Spell Correction, along with Grammar Error Suggestions, I guess you need special datasets for these purposes. You may use published models as the pretraining.
