### ISSUE TITLE
What kind of data format do you use?

### ISSUE THREAD

**Issue by kouhonglady** [grammarly/gector#53]
python utils/preprocess_data.py -s SOURCE -t TARGET -o OUTPUT_FILE

What is the SOURCE and TARGET ? All the datasets your paper mentened，can get the m2 format，but how can I get the  SOURCE  or TARGET ?

**Comment by skurzhanskyi** [comment]
As we mentioned in https://github.com/grammarly/gector/issues/10, `preprocess_data.py` takes parallel files as input (`--source` and `--target` parameters).
It's just a standard parallel files format, where each row in a source file corresponds to row in a target one.
For example, source file:
`I likes football .`
target file:
`I like football .`

**Comment by kouhonglady** [comment]
All the datasets that I got are in the format m2:
https://www.cl.cam.ac.uk/research/nl/bea2019st/#data 
How to convert format m2 to format "target" you mented？
![image](https://user-images.githubusercontent.com/26353454/90859202-4e948580-e3ba-11ea-9fc9-57666d5367ea.png)

The above example can hence be interpreted as follows:
Annotator 0 changed "are" to "is" and inserted "good" before "sentence" to produce the correction: This is a good sentence .
Annotator 1 changed "are" to "is" to produce the correction: This is a sentence .
Annotator 2 thought the original was correct and made no changes to the sentence: This are a sentence .

**The source is " This are a sentence ."  but what is the target ? "This is a good sentence . " or " This is a sentence . "**

**Comment by Chhokra** [comment]
> All the datasets that I got are in the format m2:
> https://www.cl.cam.ac.uk/research/nl/bea2019st/#data
> How to convert format m2 to format "target" you mented？
> ![image](https://user-images.githubusercontent.com/26353454/90859202-4e948580-e3ba-11ea-9fc9-57666d5367ea.png)
> 
> The above example can hence be interpreted as follows:
> Annotator 0 changed "are" to "is" and inserted "good" before "sentence" to produce the correction: This is a good sentence .
> Annotator 1 changed "are" to "is" to produce the correction: This is a sentence .
> Annotator 2 thought the original was correct and made no changes to the sentence: This are a sentence .
> 
> **The source is " This are a sentence ." but what is the target ? "This is a good sentence . " or " This is a sentence . "**

One thing you could do is read the json files. FCE has their data both in JSON and M2 format.

**Comment by Chhokra** [comment]
@skurzhanskyi @komelianchuk  , I have the same question - since all the datasets are in m2 format and not a parallel corpus - how does one convert them into a parallel corpus?(Reverse of what Errant achieves)

**Comment by komelianchuk** [comment]
For most datasets, it is possible to find a version of data in parallel files format (where you have source and target separated).
If it is not possible, then you need to write a custom script in order to do that (try to apply all annotations one by one to the source sentence)

**Comment by mtorabirad** [comment]
@skurzhanskyi what is the role of the OUTPUT_FILE here?
