### ISSUE TITLE
About the dataset of stage 1

### ISSUE THREAD

**Issue by EdwardZH** [grammarly/gector#54]
I have processed the data of stage 1. I got 44326735 pairs and I found that gector uses 9000000 pairs in experiments. Do you sample training data in your experiments?

**Comment by komelianchuk** [comment]
As we mentioned in the paper, we used only a subset of synthetic data (first 9 million sentences).

**Comment by EdwardZH** [comment]
Thank you very much.

**Comment by EdwardZH** [comment]
Thank you very much.
