### ISSUE TITLE
What methodology was used in selecting only errorful sentences for stage 2 and a mix of error-free and errorful sentences for stage 3?

### ISSUE THREAD

**Issue by Chhokra** [grammarly/gector#56]
Moreover, what exact number of datapoints went into both the stages of training?

**Comment by komelianchuk** [comment]
We filtered all error-free sentences during stage2 by setting the `tn_prob` parameter to 0.
During stage3 we did not filter anything (`tn_prob=1`).

You can find information about the number of sentences during each stage in the paper (table 1).

**Comment by Chhokra** [comment]
> We filtered all error-free sentences during stage2 by setting the `tn_prob` parameter to 0.
> During stage3 we did not filter anything (`tn_prob=1`).
> 
> You can find information about the number of sentences during each stage in the paper (table 1).

The table 1 says that WI+Locness was split between stage 2 and stage 3. Am I correct in assuming that it was a 50-50 split between the two stages?

**Comment by komelianchuk** [comment]
It was not split.
We used WI+Locness during both stage2 and stage3. 
The only difference is that during stage2 it was cleaned from error-free sentences.

**Comment by enkaranfiles** [comment]
hi there,
ı cannot find wi+locness dataset in paralel file format. Now, ı am able to use ice dataset which was xml format, and ı converted into paralel file format in the given script. can we able to use wi+locness in m2 format?
