### ISSUE TITLE
The final model had bad performance on spellchecking. How can I solve this?

### ISSUE THREAD

**Issue by miaodl** [grammarly/gector#57]
The final model had bad performance on spellchecking. How can I solve this?
Should I add extra dataset in each stage?

**Comment by komelianchuk** [comment]
If your input text suffers from spellchecking errors a lot, I would suggest preprocessing it with a separate spellchecking system before applying GECToR.

**Comment by miaodl** [comment]
> If your input text suffers from spellchecking errors a lot, I would suggest preprocessing it with a separate spellchecking system before applying GECToR.

Thanks to you reply.  At present, I actually use a individual spellchecking system like "pyenchant", but this system always give a non-contextual suggestion while the error word is too short or fuzzy ( eg: thi --> the or this ? ). So what I think about is 1) merging this contextual feature into the dataset or 2) training another contextual spellcheking system. But considering the latency the 2) may not be a good choice. Do you have any suggestions?

**Comment by miaodeliang** [comment]
Thanks to you reply. At present, I actually use a individual spellchecking system like "pyenchant", but this system always give a non-contextual suggestion while the error word is too short or fuzzy ( eg: thi --> the or this ? ). So what I think about is 1) merging this contextual feature into the dataset or 2) training another contextual spellcheking system. But considering the latency the 2) may not be a good choice. Do you have any suggestions?

**Comment by miaodl** [comment]
Thanks to you reply. At present, I actually use a individual spellchecking system like "pyenchant", but this system always give a non-contextual suggestion while the error word is too short or fuzzy ( eg: thi --> the or this ? ). So what I think about is 1) merging this contextual feature into the dataset or 2) training another contextual spellcheking system. But considering the latency the 2) may not be a good choice. Do you have any suggestions?

**Comment by komelianchuk** [comment]
I do not think that just adding data with misspells will be enough, but you can try.
I think that the easiest way is to use a spellcheck system (for both contextual and ordinary misspells) before GECToR.
Another approach is extending tag space with g-transformations for misspells (but it's trickier and requires a model retraining).

**Comment by miaodl** [comment]
Thanks, I'll try.
