### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amejri** [grammarly/gector#60]
Hi, 
I have a question concerning the preprocess of the data. in this command: python utils/preprocess_data.py -s SOURCE -t TARGET -o OUTPUT_FILE Source target and output file correspond to what respectively ?
Thanks in advance.

**Comment by skurzhanskyi** [comment]
That question appeared in https://github.com/grammarly/gector/issues/10 & https://github.com/grammarly/gector/issues/53.
Please take a look on them.

**Comment by amejri** [comment]
Thanks a lot !

**Comment by skurzhanskyi** [comment]
Sure, if you'll have additional questions feel free to reopen.
