### ISSUE TITLE
 How to get transformation tags , for an input sentence ?

### ISSUE THREAD

**Issue by sidarth16** [grammarly/gector#62]
As of now passing an input sentence ,  the model is returning me corrected sentence . 
Adding to it , how to also **get the data about the corrected transformational tags**  for each sentence as shown in the appendix.. 
![image](https://user-images.githubusercontent.com/38394431/95092237-08ff0280-0745-11eb-9063-f42d0badb40b.png)

**Comment by komelianchuk** [comment]
Hi!
The easiest way to get these tags is by tweaking the `handle_batch` method which is using in `predict.py`
Tags are applied during the postprocess stage, so you need to explicitly force them to return.
https://github.com/grammarly/gector/blob/master/gector/gec_model.py#L247
