### ISSUE TITLE
min_error_probability wrong?

### ISSUE THREAD

**Issue by YueCongPKU** [grammarly/gector#64]
In predict.py,

![image](https://user-images.githubusercontent.com/5901729/96682042-d4c54c00-13aa-11eb-9941-6e90bd683d54.png)

line 35,36:
                         min_error_probability=args.min_error_probability,
                         min_probability=args.min_error_probability,

Is min_error_probability and min_probability the same? Or it's just a bug?

**Comment by skurzhanskyi** [comment]
Indeed, it should be the same variable. Yes, it's a bug. 
Thanks for noticing. We'll fix it later.
