### ISSUE TITLE
Error in loading state_dict for Seq2Labels: Missing keys(s) in state_dict

### ISSUE THREAD

**Issue by ZiningZhu** [grammarly/gector#67]
This was raised in #39 and #49 but I encountered this error in a different situation. I tried to use the pretrained models from grammarly-nlp-data-public.s3.amazonaws.com.  

Command I used:  
```
python predict.py --model_path models/roberta_1_gector.th \
--vocab_path data/output_vocabulary \
--transformer_model roberta \
--input_file test_input.txt \
--output_file test_output.txt
```

The output:  
```
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "gector/gector/gec_model.py", line 92, in __init__
    model.load_state_dict(torch.load(model_path))
  File "usr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	Missing key(s) in state_dict: "text_field_embedder.token_embedder_bert.bert_model.embeddings.position_ids". 
```

Any hints on solving this would be helpful. Thank you.

**Comment by skurzhanskyi** [comment]
That's strange. Do you use the same version of AllenNLP, as it's in the requirements?

**Comment by komelianchuk** [comment]
It seems that you are using a newer version of `transformers` library (different from the one that we have in requirements.txt)

**Comment by ZiningZhu** [comment]
I’m using allennlp 0.8.5, pytorch 1.3.1, and transformers 3.1.0

**Comment by komelianchuk** [comment]
`position_ids` were added only in transformers 3.*, but we used transformers==2.2.2 w/o them.

**Comment by ZiningZhu** [comment]
I switched to using the requirements.txt specs (transformers==2.2.2, sentencepiece 0.1.91) and the `roberta` model runs well!
