### ISSUE TITLE
Some drawbacks in the specific GEC task

### ISSUE THREAD

**Issue by KYRIEZX** [grammarly/gector#68]
Your model might regard a word plus a punctuation as a single token, that makes some problems. For example, "I like apple.", model might  want to add "s" for "apple", but the "apple." is regarded as a single token. Eventually the output is "I like apple.ssss". This kind of cases are very common  during some specific GEC tasks, and I wonder which part of  your code is about the tokenization? Thx

**Comment by skurzhanskyi** [comment]
We assume that our input is already tokenized. Just like in our train and test data.
