### ISSUE TITLE
Evaluate ensembles

### ISSUE THREAD

**Issue by keerthinibm** [grammarly/gector#69]
Hi,
I wanted to evaluate ensembles (XLnet +roberta) for my own test data. I have both xlnet_gector and roberta_gector (.th files).
I had passed these two files in **model_paths = ["path_to_xlnet", "path_to_roberta"]** and set **is_ensemble=1.** Getting error there.
Could you specify the commands for this evaluation?

**Comment by komelianchuk** [comment]
Hi!
What kind of error did you get?
Please notice that models should be named properly: `roberta_1_something.th` (`roberta` corresponds to transformer type and `1` corresponds to special_tokens_fix parameter)

**Comment by keerthinibm** [comment]
these are the arguments that I specified.

                    **(vocab_path="data/output_vocabulary/",
                     model_paths = ["model/xlnet_0_gector.th","model/roberta_1_something.th"],
                     max_len=50, min_len=2,
                     iterations=5,
                     min_error_probability=min_error_probability,
                     min_probability=min_error_probability,
                     lowercase_tokens=0,
                     model_name='roberta',
                     special_tokens_fix=1,
                     log=False,
                     confidence=0,
                     is_ensemble=1,
                     weigths=None)**

Here is the traceback of the error:

**Traceback (most recent call last):
  File "predict.py", line 38, in <module>
    model = GecBERTModel(vocab_path=vocab_path,
  File "/home/user/sententia/gector/gector/gec_model.py", line 93, in __init__
    self.indexers.append(self._get_indexer(weights_name, special_tokens_fix))
  File "/home/user/sententia/gector/gector/gec_model.py", line 202, in _get_indexer
    bert_token_indexer = PretrainedBertIndexer(
  File "/home/user/sententia/gector/gector/wordpiece_indexer.py", line 425, in __init__
    bpe_ranks = bert_tokenizer.bpe_ranks
AttributeError: 'XLNetTokenizer' object has no attribute 'bpe_ranks'**

**Comment by keerthinibm** [comment]
I am able to fix this issue. 
Thank you.
