### ISSUE TITLE
Question about vocabulary

### ISSUE THREAD

**Issue by KYRIEZX** [grammarly/gector#71]
What's the origin of the vocabulary you provide in this model? Could the train.py script help expand the vocabulary after training?

**Comment by skurzhanskyi** [comment]
There is a method to build a vocabulary based on the training data - the most popular tags. You can tune the number of tokens in vocabulary with `target_vocab_size`.
https://github.com/grammarly/gector/blob/master/train.py#L114-L122

**Comment by KYRIEZX** [comment]
> There is a method to build a vocabulary based on the training data - the most popular tags. You can tune the number of tokens in vocabulary with `target_vocab_size`.
> https://github.com/grammarly/gector/blob/master/train.py#L114-L122

Thanks for answering! So in the code, your label vocabulary is the most popular labels built from training data, right?

**Comment by skurzhanskyi** [comment]
Yes, but you can change this number while changing `target_vocab_size`

**Comment by KYRIEZX** [comment]
> Yes, but you can change this number while changing `target_vocab_size`

That's awesome! One last question, what's this graph meaning for? It's kinda confusing.
![image](https://user-images.githubusercontent.com/56826566/99349118-2263a480-28d6-11eb-864d-3a3f75ff7047.png)
Why 10000 size vocab covers 100% of all transforms but 93.5% basic transforms? Is that paradox?

**Comment by skurzhanskyi** [comment]
We compare basic transformations which are usually used in non-autoregressive models and our extended transformations. Here we show that with 10000 basic transformations you can cover only 93.5% of edits in training data, while with 10000 extended ones - 100%.

**Comment by KYRIEZX** [comment]
> We compare basic transformations, which are usually used in non-autoregressive models, and our extended transformations. Here we show that with 10000 basic transformations you can cover only 93.5% of edits in training data, while with 10000 extended ones - 100%.


> We compare basic transformations, which are usually used in non-autoregressive models, and our extended transformations. Here we show that with 10000 basic transformations you can cover only 93.5% of edits in training data, while with 10000 extended ones - 100%.

Got it! Thank you!

**Comment by KYRIEZX** [comment]
> We compare basic transformations, which are usually used in non-autoregressive models, and our extended transformations. Here we show that with 10000 basic transformations you can cover only 93.5% of edits in training data, while with 10000 extended ones - 100%.

Got it! Thank you!

**Comment by skurzhanskyi** [comment]
Glad to help

**Comment by KYRIEZX** [comment]
> We compare basic transformations, which are usually used in non-autoregressive models, and our extended transformations. Here we show that with 10000 basic transformations you can cover only 93.5% of edits in training data, while with 10000 extended ones - 100%.

still wondering why didn't you choose to use the keep one strategy rather than merge these labels to build the vocabulary, can you ask my question?
