### ISSUE TITLE
How to preprocess the train and dev dataset in StageⅡ&Ⅲ

### ISSUE THREAD

**Issue by valueable** [grammarly/gector#74]
I wonder how to preprocess the train data in StageⅡ&Ⅲ，because i found the fce dataset and wi+locness are both json files，unlike the format of the synthetic data which are txt files？Thank you

**Comment by enkaranfiles** [comment]
did you have a any solution?

**Comment by enkaranfiles** [comment]
I have the same question! Do you have any solution for that? Thanks!

**Comment by valueable** [comment]
> I have the same question! Do you have any solution for that? Thanks!

Maybe you can download Dataset [here](https://ilexir.co.uk/datasets/index.html)，and in the /utils folder，preprocess the XML files via the prepare_clc_fce_data.py

**Comment by enkaranfiles** [comment]
yeah, ı know that link but ı cannot found wi+locness paralel file data. it contains only fce dataset. Am I right?

**Comment by valueable** [comment]
> yeah, ı know that link but ı cannot found wi+locness paralel file data. it contains only fce dataset. Am I right?

Yes, You're right, haven't found a solution yet, sorry.

**Comment by enkaranfiles** [comment]
you can use corr_from_m2.py file

**Comment by enkaranfiles** [comment]
I found a solution. You can use corr_from_m2.py file which is provided by BEA website. This script gains us to obtain correct form a sentence given m2 file.(which was our target) The question about getting source file is, you can write simple python script that take a sentence whose begin with 'S'. in the m2 file. In that way you can use all dataset and separate them into as source and target, then you able to use pre_process script.

**Comment by valueable** [comment]
Got it, I'll have a try, thanks!
