### ISSUE TITLE
[Question] Stage 1 training time

### ISSUE THREAD

**Issue by cidrugHug8** [grammarly/gector#77]
Hi there.

The progress bar does not move even after one hour of output as follows.
```
python3 train.py --cuda_verbose_steps 1000 --updates_per_epoch 100 \
  --train_set ../sample/stage1.train --dev_set ../sample/stage1.dev --model_dir ../model/stage1 \
  --n_epoch 20 --cold_steps_count 2 --accumulation_size 4 --updates_per_epoch 10000 \
  --tn_prob 0 --tp_prob 1 --pretrain ''
0it [11:46, ?it/s]
Data is loaded
Model is set
INFO:gector.trainer:initialized.
Start training
INFO:gector.trainer:Beginning training.
INFO:gector.trainer:Epoch 0/19
INFO:gector.trainer:Peak CPU memory usage MB: 3510.776
INFO:gector.trainer:GPU 0 memory usage MB: 1131
INFO:gector.trainer:Training
  0%|                                                       | 0/40000 [00:00<?, ?it/s]
```
How long will it take?

Thank you.

**Comment by cidrugHug8** [comment]
Incidentally, the data was made in the following steps:
```
SOURCE=./synthetic/a1/a1_train_incorr_sentences.txt
TARGET=./synthetic/a1/a1_train_incorr_sentences.txt
ALL_SET=../sample/stage1.all
TRAIN_SET=../sample/stage1.train
DEV_SET=../sample/stage1.dev

python3 utils/preprocess_data.py \
  -s "${SOURCE}" -t "${TARGET}" -o "${ALL_SET}"
tac "${ALL_SET}" \
  | sed -n '1001,$p' \
  | tac \
  > "${TRAIN_SET}"
tail -1000 "${ALL_SET}" \
  > "${DEV_SET}"
```

**Comment by skurzhanskyi** [comment]
Hmm, can you share your GPU/CPU configurations? 
Also, I would recommend limiting the number of training/validation examples by 1000 just for a sanity check.

**Comment by cidrugHug8** [comment]
Thank you for your reply.

I'm running with the following configuration:
- **GPU:** NVIDIA Corporation GP102 [TITAN X]
- **CPU:** Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
- **PyTorch:** 1.3.0
- **Python:** Python 3.6.9

> Also, I would recommend limiting the number of training/validation examples by 1000 just for a sanity check.

I tried and got the same situation.

**Comment by skurzhanskyi** [comment]
>I tried and got the same situation.

That means smth definitely going wrong. 

I see two discrepancies — your PyTorch & Python version are different from the ones we use. I would suggest starting with updating libraries as it's in requirements:
```
pip install -r requirements.txt
```

**Comment by cidrugHug8** [comment]
I updated Python 3.7 from 3.6.9 and executed pip.
Does it take so long to execute the following line?
```
gector/trainer.py
        for batch_group in train_generator_tqdm:
```
Is the way to prepare the data correct?

**Comment by cidrugHug8** [comment]
It's been 36 hours since I started running and I haven't made any progress, not even 1%.
I don't know what to do. I don't know if this behavior is normal.

**Comment by komelianchuk** [comment]
Hi, @cidrugHug8 
36 hours definitely does not seem normal (however ~1-hour delay is expected behavior for  updates_per_epoch=10000)

I would suggest set `cuda_verbose_steps` to None, `updates_per_epoch` to 0, `batch_size` to 8 and try again with a 1000 lines dataset.

**Comment by cidrugHug8** [comment]
Thank you for your advice.
I've executed as you suggested, now I got the following result.
![image](https://user-images.githubusercontent.com/11013023/100710172-ab103380-33f2-11eb-9090-c2b2c8089ab5.png)
Is this normal?
Does this mean that it takes longer to run in my environment?

**Comment by komelianchuk** [comment]
I think it should work fine with your original setup as well (just take more time on data preparing). 
I suggest just rerun it on your original data with: 
- cuda_verbose_steps = None (we used it only for debugging) 
- updates_per_epoch=10000
and wait for more than 1 hour.
How many sentences do you have in your train/dev files?

**Comment by cidrugHug8** [comment]
@komelianchuk @komelianchuk 
I finally figured out why it failed. 
I had made a mistake in the pre-processing of the data.
Thanks so much for all the advice, both of you.

**Comment by DUT-LiuYang** [comment]
> I finally figured out why it failed.
> I had made a mistake in the pre-processing of the data.
> Thanks so much for all the advice, both of you.

hi，@cidrugHug8 I met a similar problem. How did you solve it? Thank you~

**Comment by cidrugHug8** [comment]
@DUT-LiuYang 
The source language and destination language were reversed.

**Comment by Anddyyyyy** [comment]
> @DUT-LiuYang The source language and destination language were reversed.

Hi, i met the same problem, but i check the source language and target language. I didn't find the problem, how did you solve it ? Thank you
