### ISSUE TITLE
The pre - trained models are much heavy to run online.

### ISSUE THREAD

**Issue by shikha10799** [grammarly/gector#8]
The pretrained models are very large. Not having proper architecture (GPU's),i tried to run them on colab but they are too heavy heavy to be uploaded online.Is there any other alternative (if i run on colab) in order to reproduce the results.

**Comment by skurzhanskyi** [comment]
Hi @shikha10799
Yes, it's supposed that you have GPU to run the model.
In Google Colab you may get different GPUs, so it depends on what particular GPU you get.
I would also recommend you to try Kaggle Kernels.

**Comment by shikha10799** [comment]
ok thanks.
