### ISSUE TITLE
Difference in formats of test files

### ISSUE THREAD

**Issue by khatrimann** [grammarly/gector#81]
Hey, when we use errant for creation of m2 file using parallel corpus, we get edits with corrections like ```A 1 1|||M:PUNCT|||,|||REQUIRED|||-NONE-|||0``` but in CoNLL we have annotations like this ```A 1 1|||Trans|||,|||REQUIRED|||-NONE-|||0```. So will there be any problem while using ```errant_compare```. And how can we switch between both the formats?

**Comment by skurzhanskyi** [comment]
Both formats are m2; the difference is only in error type naming. To the best of my knowledge, M2Scorrer doesn't use error type to set the score, while ERRANT relies on error types. As a result, you can evaluate m2 files with different error type namings in M2Scorrer, but cannot in ERRANT. 
In our paper (and usually in papers), ERRANT is used for BEA19, while M2Scorrer is used for CoNLL-14.

**Comment by khatrimann** [comment]
I am using this [conll](https://www.comp.nus.edu.sg/~nlp/conll14st/conll14st-test-data.tar.gz) from [this page](https://www.comp.nus.edu.sg/~nlp/conll14st.html) and using ```noalt``` version of the dataset containing 1313 sentences. M2 is giving me the following results:

```
Precision   : 0.7397
Recall      : 0.4168
F_0.5       : 0.6405
```

but in paper the results are different.

**Comment by khatrimann** [comment]
Is (this)[https://competitions.codalab.org/competitions/20230#learn_the_details] the link for bea19 test set?

**Comment by skurzhanskyi** [comment]
Yes. That's the idea, BEA19 test set's references are hidden, you can only find source sentences.
