### ISSUE TITLE
pretrain model can t load

### ISSUE THREAD

**Issue by jacobunderlinebenseal** [grammarly/gector#84]
Do you have any idea how to fix this

Traceback (most recent call last):
  File "predict.py", line 114, in <module>
    main(args)
  File "predict.py", line 42, in main
    weigths=args.weights)
  File "/workspace/gector/gector/gec_model.py", line 93, in __init__
    model.load_state_dict(torch.load(model_path))
  File "/home/work/.conda/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
        size mismatch for text_field_embedder.token_embedder_bert.bert_model.embeddings.word_embeddings.weight: copying a param with shape torch.Size([28996, 768]) from checkpoint, the shape in current model is torch.Size([28997, 768]).

**Comment by johannschenkl** [comment]
We had the same issue on out side. I suppose you're trying to use BERT as the pretrained model. To make it work the cmd call needs to be:

`python predict.py --model_path MODEL_PATH --vocab_path VOCAB_PATH  --input_file INPUT_FILE  --output_file OUTPUT_FILE --special_tokens_fix 0 --transformer_model bert`

At least this worked for us.

**Comment by skurzhanskyi** [comment]
Thanks @johannschenkl for the clarification. 
Indeed, as it was mentioned in multiple previous issues, you need to specify `--special_tokens_fix` parameter.
