### ISSUE TITLE
Model unlearned

### ISSUE THREAD

**Issue by keerthinibm** [grammarly/gector#85]
Hi,

I have trained the model in three-stage with suggested respective training parameters using the suggested dataset but introducing necessary perturbations that I required.

I have taken the best model and vocabulary from previous stage to train the next stages. 

At stage1, it learned well, but at stage2, it has forgotten many things that have been learned at stage1. Even after I trained the model for stage3, there also the same thing happened.

ex:
	i/p: This is required materials.

stage1: 
	o/p: This is the required material.

stage2:
	o/p: This is the required materials.

stage3:
	o/p: This is a required materials.

So what could be the reason for this UNLEARNING? How can I overcome this problem?

**Comment by skurzhanskyi** [comment]
It isn't easy to sort out with such little information.
In any case, you can try to use our pretrained models (links in README).
