### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by PamelaDDD** [grammarly/gector#87]
Hello, I would like to ask if you can send some pre-processed samples. I am not sure whether my pre-processed data is consistent with your input format. During training, the program got stuck in the training epoch and could not continue to run. I guess it was a data loading problem.
I try to debug，the process got stuck at :
![image](https://user-images.githubusercontent.com/33123364/105566450-45dc1d00-5d67-11eb-9313-19042c7634ee.png)

**Comment by skurzhanskyi** [comment]
Sorry for the late reply. I suppose the problem is indeed in the data processing. Did you use `preprocess_data.py` for this purpose?
