### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by hontarenkoYana** [grammarly/gector#88]
Hello!
I have to notice that GECToR is a great work! 

Could somebody answer, is in this repository is mechanism or opportunity to fine-tuning GECToR? For example, I want tune it to be more accurate in lexical correction and I have data for this?

**Comment by skurzhanskyi** [comment]
Hi @hontarenkoYana 
Thanks. You can fine-tune existing models (links for weights [here](https://github.com/grammarly/gector#pretrained-models)) with hyperparameters similar to our [Stage 3](https://github.com/grammarly/gector/blob/master/docs/training_parameters.md#stage3-parameters).

**Comment by hontarenkoYana** [comment]
Thank you for response, @skurzhanskyi 
But what the way? 
I need to load weights and that start training, yes? That is all?)

**Comment by skurzhanskyi** [comment]
If you have your own dataset, you need to convert it to a parallel format and then process it with [preprocess_data.py](https://github.com/grammarly/gector/blob/master/utils/preprocess_data.py). 
> I need to load weights and that start training, yes?

And then basically yes.

**Comment by hontarenkoYana** [comment]
Great! @skurzhanskyi, thank you!
