### ISSUE TITLE
How do i use multiple models at the same time in the predict script, also how to use gpt2?

### ISSUE THREAD

**Issue by geekjr** [grammarly/gector#90]
Hi. I see in the README, you have shown performance metrics for multiple models put together. How can i run the predict with multiple models? Also, how do i use GPT-2?

**Comment by skurzhanskyi** [comment]
To use an ensemble of models, you need to pass multiple paths to the `predict.py` with `--model_path` parameter. An important note here — if you use our pretrained models, don't change the names of files. 
Regarding GPT-2, as the preliminary results of GPT-2 were unsatisfied, we didn't train all stages with GPT-2, thus didn't publish its weights.
