### ISSUE TITLE
Extension to other languages?

### ISSUE THREAD

**Issue by mtorabirad** [grammarly/gector#93]
@skurzhanskyi Do you guys have any inputs on how this can be extended to other languages?

**Comment by skurzhanskyi** [comment]
It all depends on the data you have. If you have good-quality data in other languages, you can try to build your model following a similar pipeline. At least you may try to train it on synthetic corrupted data and check if it works.

**Comment by mtorabirad** [comment]
thank you @skurzhanskyi.

**Comment by mtorabirad** [comment]
@skurzhanskyi I trained on German using Falko-Merlin dataset and got the following test scores: 
Precision=0.59, Recall=0.199, F_0.5=0.4241. 

I want to get closer to the scores reported in Table 6 of "Náplava, J., & Straka, M. (2019). Grammatical error correction in low-resource scenarios. arXiv preprint arXiv:1910.00353." 

I understand that by training longer, my recall/precision will increase/decrease, so I plan to do that. Any other suggestions that will improve the scores and hopefully get them closer to the best scores in the Table?? Thank you!

**Comment by skurzhanskyi** [comment]
I'm not familiar with German GEC, but I recommend preparing synthetic data to train your model on it before fine-tuning on the human-annotated dataset.
Also, GECToR has transforms specific to the English language, so you may want to build your own ones for the German language.

**Comment by mtorabirad** [comment]
Thank you @skurzhanskyi for the comment. Would you minding giving me some hints on how I should go about building a transformer from scratch?

**Comment by skurzhanskyi** [comment]
I think I already told you everything I had in mind. If you have specific questions, do not hesitate to open issues.

**Comment by federicoBetti** [comment]
Hi @mtorabirad. I am interested in this too. 
Do you have any update on it? 
I was thinking about adding german-specific g-transformation as target and using german bert as pretrained backbone. 

Best
