### ISSUE TITLE
Can I use this model on Chinese GEC?

### ISSUE THREAD

**Issue by Hexa4C** [grammarly/gector#94]
Hi, I am trying to use this model on Chinese GEC. I do not know if it is possible.
I've just changed the `weights_name` and tokenizer etc.
But I stuck in vocabulary. It seems that we have to use the output_vocabulary file you provided? 
And I cannot find any information about how to train the model from the beginning.

**Comment by skurzhanskyi** [comment]
Hi, I believe it's possible to train the model for another language. It's a matter of data.
The only downside is that there're transforms that are created specifically for the English language. So you may want to create your own ones.
To build vocabulary from training data use should simply do not specify vocabulary path in `train.py`:
https://github.com/grammarly/gector/blob/master/train.py#L195-L197

**Comment by Hexa4C** [comment]
Thanks , I will try.

**Comment by HeroadZ** [comment]
@Hexa4C Hi, how's going about Chinese GEC? 
I'm new to GEC and try to apply it to Japanese GEC. 
Could you give some advice if you have good progress?

**Comment by skurzhanskyi** [comment]
And again, it may be crucial to create Chinese-specific transforms. If you don't do it, you will only operate with simple actions like delete, replace, append, swap.

**Comment by skurzhanskyi** [comment]
Actually, you can gather some good transforms just using statistics. It can be common errors: misspellings, tense changes (if these are common in the Chinese language), etc.
