### ISSUE TITLE
How long it takes to train on single GPU?

### ISSUE THREAD

**Issue by JackieHanC** [grammarly/gector#96]
Hi,
I'd like to ask how long it takes to train on single GPU for 3 stages, respectively?

**Comment by skurzhanskyi** [comment]
Hi
That depends on what particular GPU you have

**Comment by skurzhanskyi** [comment]
In our experiments, we trained our model on a single NVIDIA Tesla V100, and it took about 5 days in total. In particular:
- stage 1 ~ 4 days
- stage 2 ~ 0.5 day
- stage 3 ~ 2 hours

**Comment by JackieHanC** [comment]
Thanks!

**Comment by skurzhanskyi** [comment]
As it's described in the paper Stage 1 is training on synthetically generated data. It improves the final scores, but you still can get quite good scores while omitting it.
