### ISSUE TITLE
Use GEC with latest transformer, allennlp modules

### ISSUE THREAD

**Issue by Jiltseb** [grammarly/gector#98]
I want to use GEC on a latest transformer model (v4.4.2). However, it has several module errors in gector and seems difficult to fix. I have tried using v1.5.0 of allennlp but was running into errors.

Note: There is no issue in getting the GEC work with the specified versions in requirements.txt. It is just that, I want to use it in a virtual environment with latest transformer/allennlp versions.

Any help is highly appreciated! @skurzhanskyi

**Comment by abhinavdayal** [comment]
I also tried with the latest versions. It seems a lot of code is using deprecated functionality that need to be re-written.

**Comment by Jiltseb** [comment]
@skurzhanskyi any news on this? We are still stuck with this.

**Comment by Ierezell** [comment]
Hi, any update on this ? 

I had to change the code to make it fit with new allennlp (I can do a PR if needed), but I'm still facing many issues while loading models or running predicitons. 

I tried both 3 pretrained models and cannot make any of them to work.... 

Thanks in advance

**Comment by skurzhanskyi** [comment]
Hi, there's a branch with the `transformer==4.2.2`. You can check it here:
https://github.com/grammarly/gector/tree/update_transformers_support_fasttokenizers
At the same time, pretrained models produce pure output with this code. we're in the middle of retraining the models.

**Comment by Ierezell** [comment]
Hi @skurzhanskyi, I just tried but unfortunately, I got the same errors... 

I'm trying to use directly the GecBERTModel class to integrate it into my code. 
I have a higher version of allennlp but I modified imports to work with it, however most of the errors come from missing keys or bad loading of the models. 

I will wait for the new release.

Have a great day

**Comment by Jiltseb** [comment]
@skurzhanskyi  Any update on the release with the new retrained models?
